---
title: "PCA"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
polarity <- "NEG" # specify "POS" or "NEG"
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
```

# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
tmp$X2 <- paste(tmp$X2, tmp$X3, sep = "_")
tmp <- tmp[,-3]
colnames(tmp) <- c("order", "project", "pt", "tissue", "rep", "polarity", "mode")
tmp$tissue[grep("QC", tmp$pt)] <-paste(tmp$pt[grep("QC", tmp$pt)], tmp$tissue[grep("QC", tmp$pt)], sep = "_")
tmp$pt[grep("QC", tmp$pt)] <- "xx00"
injections <- cbind(injections, tmp)
rm(tmp)
injections$color <- 1
injections$color[injections$tissue == "QC"] <- 2   # red
injections$color[injections$pt == "pt11"] <- 3 # green
injections$color[injections$tissue == "solv"] <- 4   # blue
injections$color[injections$tissue == "solveq"] <- 5 # cyan
injections$color[injections$type == "QCeq"] <- 6  # pink
injections$color[grep("QCdl", injections$tissue)] <- 7 # yellow
injections$color[grep("QCrw", injections$tissue)] <- 7 # yellow
injections$color[injections$tissue == "STDmix"] <- 8  # grey

injections <- injections[grep("solv_rep1", injections$filename):nrow(injections),]
injections <- injections[injections$pt == "pt11", ]

# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# XCMS processing

```{r xcms}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, 1e5),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)

pdp <- PeakDensityParam(sampleGroups = xdata$tissue,
                        minFraction = 0.75,
                        binSize = 0.02,
                        bw = 3)
xdata <- groupChromPeaks(xdata, param = pdp)

pgp <- PeakGroupsParam(span = 0.3,
                       #subset = which(xdata$tissue == "QC"),
                       #subsetAdjust = "average",
                       minFraction = 0.3)
xdata <- adjustRtime(xdata, param = pgp)

pdp <- PeakDensityParam(sampleGroups = xdata$tissue,
                        minFraction = 0.66,
                        minSamples = 1,
                        binSize = 0.02,
                        bw = 1)
xdata <- groupChromPeaks(xdata, param = pdp)

fcp <- ChromPeakAreaParam()
xdata <- fillChromPeaks(xdata, param = fcp)
```


# PCA

```{r pca}
data <- featureValues(xdata, method = "sum", value = "into")
set.seed(123)
data <- t(imputeRowMinRand(data, method = "from_to",
                           min_fraction = 1/100,
                           min_fraction_from = 1/1000
))
dt <- log10(data)
scaling.pareto <- BioMark::scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))

pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plotly::plot_ly(x = tmp$PC1, y = tmp$PC2,
                text = gsub(".mzData", "", rownames(tmp)),
                color = xdata$tissue)

features <- data.frame(featureDefinitions(xdata))
tmp <- data.frame(pca$rotation)
plotly::plot_ly(x = tmp$PC1, y = tmp$PC2,
                text = paste("mz:", round(as.numeric(features$mzmed), 4), 
                             "RT:", round(features$rtmed)))
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```