---
title: "Identification"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Parameters

```{r parameters}
z.polarity <- "POS" # specify "POS" or "NEG"

if(z.polarity == "NEG"){
  z.back <- 158.9753
} else if (z.polarity == "POS"){
  z.back <- c(251.164, 283.6995)
}
```

# Libraries

```{r libraries, message=FALSE}
library(Rdisop)
library(OrgMassSpecR)
library(CompoundDb)
library(xcms)
library(plotly)
library(MsCoreUtils)
```


# Compound database

```{r compounds}
cmps <- read.csv("../compounds_RT_formula.csv")
cmps <- cmps[cmps$class == "IS", ]


ions <- data.frame(matrix(nrow = 0, ncol = 5))
for(i in 1:nrow(cmps)){
  if(z.polarity == "NEG"){
    if(grepl("D", cmps$formula[i])){
      ions <- rbind(
        ions, 
        cbind(rep(cmps$C[i], 4), rep(cmps$ID[i], 4), rep(cmps$RT[i]*60, 4), 
              unlist(mass2mz(getMolecule(cmps$formula[i])$exactmass, 
                             adduct = c("[M-H]-", "[M+Cl]-", "[M-H+HCOOH]-", 
                                        "[2M-H]-"))), 
              c("[M-H]-", "[M+Cl]-", "[M-H+HCOOH]-", "[2M-H]-")))
    } else {
      ions <- rbind(
        ions, 
        cbind(rep(cmps$C[i], 4), rep(cmps$ID[i], 4), rep(cmps$RT[i]*60, 4), 
              unlist(mass2mz(MonoisotopicMass(
                cmps$formula[i], formula = ListFormula(cmps$formula[i])), 
                adduct = c("[M-H]-", "[M+Cl]-", "[M-H+HCOOH]-", "[2M-H]-"))), 
              c("[M-H]-", "[M+Cl]-", "[M-H+HCOOH]-", "[2M-H]-")))
    }
  } else if(z.polarity == "POS"){
    if(grepl("D", cmps$formula[i])){
      ions <- rbind(
        ions, 
        cbind(rep(cmps$C[i], 6), rep(cmps$ID[i], 6), rep(cmps$RT[i]*60, 6), 
              unlist(mass2mz(getMolecule(cmps$formula[i])$exactmass, 
                             adduct = c("[M+H]+", "[M+NH4]+", "[M+Na]+", 
                                        "[M+K]+", "[2M+H]+", "[2M+Na]+"))), 
              c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", "[2M+H]+", 
                "[2M+Na]+")))
    } else {
      ions <- rbind(
        ions, 
        cbind(rep(cmps$C[i], 6), rep(cmps$ID[i], 6), rep(cmps$RT[i]*60, 6), 
              unlist(mass2mz(MonoisotopicMass(
                cmps$formula[i], formula = ListFormula(cmps$formula[i])), 
                adduct = c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", 
                           "[2M+H]+", "[2M+Na]+"))), 
              c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", "[2M+H]+", 
                "[2M+Na]+")))
    }
  }
}
colnames(ions) <- c("C", "ID", "RT", "mz", "annotation")
ions$RT <- as.numeric(ions$RT)
ions$mz <- as.numeric(ions$mz)
rm(i)

if(z.polarity == "NEG"){
  cmps_ft <- read.csv("../compounds_features.csv")
  cmps_ft <- cmps_ft[cmps_ft$polarity == z.polarity, ]
  cmps_ft$ID <- NA
  cmps_ft$RT <- NA
  for(i in seq(nrow(cmps_ft))){
    cmps_ft$ID[i] <- cmps$ID[cmps$C == cmps_ft$C[i]]
    cmps_ft$RT[i] <- cmps$RT[cmps$C == cmps_ft$C[i]]*60
    if(grepl("C", cmps_ft$mz[i])){
      if(z.polarity == "POS"){
        cmps_ft$mz[i] <- getMolecule(cmps_ft$mz[i])$exactmass + 1.007276
      } else if(z.polarity == "NEG"){
        cmps_ft$mz[i] <- getMolecule(cmps_ft$mz[i])$exactmass - 1.007276
      }
    }
  }
  cmps_ft$mz <- as.numeric(cmps_ft$mz)
  cmps_ft <- subset(cmps_ft, select = c("C", "ID", "RT", "mz", "annotation"))
  ions <- rbind(ions, cmps_ft)
}

cmps_unk <- read.csv("data/IS_unknowns.csv")
cmps_unk <- cmps_unk[cmps_unk$polarity == z.polarity, ]
cmps_unk <- cmps_unk[,-ncol(cmps_unk)]
cmps_unk$ID <- NA
for(i in seq(nrow(cmps_unk))){
  if(cmps_unk$C[i] %in% cmps$C){
    cmps_unk$ID[i] <- cmps$ID[cmps$C == cmps_unk$C[i]]
  } else {
    cmps_unk$ID[i] <- paste("Unknown", cmps_unk$C[i])
  }
}
ions <- rbind(ions, cmps_unk)

```

# Data import

```{r import}
load(paste0("data/RData/IS_data_XCMS_", z.polarity, ".RData"))
data <- featureValues(xdata, method = "sum", value = "into")
data[is.na(data)] <- 0
features <- data.frame(featureDefinitions(xdata))
features$mean_solv <- rowMeans(data[,xdata$tissue == "solv"])
features$mean_blank <- rowMeans(data[,xdata$tissue == "blank"])
features$mean_blank_no <- rowMeans(data[,xdata$tissue != "blank"])
features$mean_STDmix <- rowMeans(data[,xdata$tissue == "STDmix"])
```


# Identification

```{r identification}
features$C <- NA
features$compound <- NA
features$annotation <- NA
features$ppm <- NA
features$RT_d <- NA

x.ppm = 10

for(i in seq(nrow(features))){
  cmp.i <- ions[unlist(matchWithPpm(features$mzmed[i], ions$mz, ppm = x.ppm)),]
  cmp.i <- cmp.i[abs(features$rtmed[i] - cmp.i$RT) < 30, ]
  if(nrow(cmp.i) > 0){
    if(any(grepl("Unknown", cmp.i$ID))){
      cmp.i <- cmp.i[which.min(abs(features$rtmed[i] - cmp.i$RT)), ]
    }
    features$C[i] <- paste(cmp.i$C, collapse = "; ")
    features$compound[i] <- paste(cmp.i$ID, collapse = "; ")
    features$annotation[i] <- paste(cmp.i$annotation, collapse = "; ")
    features$ppm[i] <- paste(sprintf("%.1f", round(
      ((features$mzmed[i] - cmp.i$mz)/cmp.i$mz)*1e6, 1)), collapse = "; ")
    features$RT_d[i] <- paste(round(features$rtmed[i] - cmp.i$RT), 
                              collapse = "; ")
    
    # isotopes 
    fts <- features[features$rtmed > (features$rtmed[i] - 2) & 
                      features$rtmed < (features$rtmed[i] + 2), ]
    
    ## 13 C
    idx <- unlist(matchWithPpm(features$mzmed[i] + 1.003355, 
                               fts$mzmed, ppm = x.ppm))
    if(length(idx) > 0){
      idx <- which(rownames(features) == rownames(fts)[idx])
      i.xdata <- readMSData(
        files = paste0("data/", z.polarity, "_FS_fixed/", 
                       names(which.max(data[i,]))),
        mode = "onDisk")
      chr <- chromatogram(i.xdata, mz = features$mzmed[i] + 0.01 * c(-1, 1))
      chr <- chromPeaks(findChromPeaks(
        chr, param = CentWaveParam(peakwidth = c(2, 20))))
      chr <- chr[which.min(abs(chr[, "rt"] - features$rtmed[i])), "rt"]
      sps <- as.data.frame(i.xdata[[closest(chr, rtime(i.xdata))]])
      
      if(length(unlist(matchWithPpm(features$mzmed[i] + 1.003355, sps, 
                                    ppm = x.ppm))) > 0){
        if(sps[unlist(matchWithPpm(features$mzmed[i], sps, ppm = x.ppm)), "i"] > 
           sps[unlist(matchWithPpm(features$mzmed[i] + 1.003355, 
                                   sps, ppm = x.ppm)), 
               "i"]){
          features$C[idx] <- paste(cmp.i$C, collapse = "; ")
          features$compound[idx] <- paste(cmp.i$ID, collapse = "; ")
          features$annotation[idx] <- paste(paste0("13C", cmp.i$annotation), 
                                            collapse = "; ")
          features$ppm[idx] <- paste(sprintf("%.1f", round(
            ((features$mzmed[idx] - (cmp.i$mz + 1.003355)) / 
               (cmp.i$mz + 1.003355))*1e6, 1)), collapse = "; ")
          features$RT_d[idx] <- paste(round(features$rtmed[i] - cmp.i$RT), 
                                      collapse = "; ")
          
          ## (2)13C
          idx <- unlist(matchWithPpm(features$mzmed[i] + 1.003355*2, 
                                     fts$mzmed, ppm = x.ppm))
          if(length(idx) > 0){
            idx <- which(rownames(features) == rownames(fts)[idx])
            if(sps[unlist(matchWithPpm(features$mzmed[i] + 1.003355, 
                                       sps, ppm = x.ppm)), "i"] > 
               sps[unlist(matchWithPpm(features$mzmed[i] + 1.003355*2, 
                                       sps, ppm = x.ppm)), 
                   "i"]){
              features$C[idx] <- paste(cmp.i$C, collapse = "; ")
              features$compound[idx] <- paste(cmp.i$ID, collapse = "; ")
              features$annotation[idx] <- paste(
                paste0("2(13C)", cmp.i$annotation), collapse = "; ")
              features$ppm[idx] <- paste(sprintf("%.1f", round(
                ((features$mzmed[idx] - (cmp.i$mz + 1.003355*2)) / 
                   (cmp.i$mz + 1.003355*2))*1e6, 1)), collapse = "; ")
              features$RT_d[idx] <- paste(round(features$rtmed[i] - cmp.i$RT), 
                                          collapse = "; ")
              
              ## (3)13C
              idx <- unlist(matchWithPpm(features$mzmed[i] + 1.003355*3, 
                                         fts$mzmed, ppm = x.ppm))
              if(length(idx) > 0){
                idx <- which(rownames(features) == rownames(fts)[idx])
                if(length(unlist(matchWithPpm(
                  features$mzmed[i] + 1.003355*3, sps, ppm = x.ppm))) > 0){
                  if(sps[unlist(matchWithPpm(
                    features$mzmed[i] + 1.003355*2, sps, ppm = x.ppm)), "i"] > 
                    sps[unlist(matchWithPpm(
                      features$mzmed[i] + 1.003355*3, sps, ppm = x.ppm)), 
                      "i"]){
                    features$C[idx] <- paste(cmp.i$C, collapse = "; ")
                    features$compound[idx] <- paste(cmp.i$ID, collapse = "; ")
                    features$annotation[idx] <- paste(
                      paste0("3(13C)", cmp.i$annotation), collapse = "; ")
                    features$ppm[idx] <- paste(sprintf("%.1f", round(
                      ((features$mzmed[idx] - (cmp.i$mz + 1.003355*3)) / 
                         (cmp.i$mz + 1.003355*3))*1e6, 1)), collapse = "; ")
                    features$RT_d[idx] <- paste(round(features$rtmed[i] - cmp.i$RT), 
                                                collapse = "; ")
                    
                    ## (4)13C
                    idx <- unlist(matchWithPpm(features$mzmed[i] + 1.003355*4, 
                                               fts$mzmed, ppm = x.ppm))
                    if(length(idx) > 0){
                      idx <- which(rownames(features) == rownames(fts)[idx])
                      if(length(unlist(matchWithPpm(
                        features$mzmed[i] + 1.003355*4, sps, ppm = x.ppm))) > 0){
                        if(sps[unlist(matchWithPpm(features$mzmed[i] + 1.003355*3, 
                                                   sps, ppm = x.ppm)), "i"] > 
                           sps[unlist(matchWithPpm(features$mzmed[i] + 1.003355*4, 
                                                   sps, ppm = x.ppm)), 
                               "i"]){
                          print(i)
                        }
                      }
                    } # close (4)13C
                  } 
                }
              } # close (3)13C
            }
          } # close (2)13C
        }
      }
    } # close 13C
  } # close if(nrow(cmp.i) > 0)
}

for(i in seq(length(z.back))){
  idx <- unlist(matchWithPpm(z.back[i], features$mzmed, ppm = 10))
  features$C[idx] <- paste0("B0000", seq(length(idx)))
  if(length(z.back) > 1){
    features$compound[idx] <- paste("Background", i, "-", seq(idx))
  } else {
    features$compound[idx] <- paste("Background", "-", seq(idx))
  }
  if(z.polarity == "NEG"){
    features$annotation[idx] <- "[M-H]-"
  } else if(z.polarity == "POS"){
    features$annotation[idx] <- "[M+H]+"
  }
}

write.csv(features[,-which(colnames(features) == "peakidx")], 
          paste0("data/IS_identifications_", z.polarity, ".csv"), 
          row.names = TRUE)
```


# PCA

```{r pca}
data <- featureValues(xdata, method = "sum", value = "into")
set.seed(123)
data <- t(imputeRowMinRand(data, method = "from_to",
                           min_fraction = 1/100,
                           min_fraction_from = 1/1000
))
dt <- log10(data)
scaling.pareto <- BioMark::scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = gsub(".mzData", "", rownames(tmp)),
        color = xdata$tissue)

tmp <- data.frame(pca$rotation)
rownames(tmp) <- paste(sprintf("%.4f",round(features$mzmed, 4)), 
                       sprintf("%.2f",round(features$rtmed/60, 2)), 
                       sep = "_")
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp),
        color = (!is.na(features$compound) & features$compound != "Background"), 
        colors = "Set2")
```


# Table

```{r table}
features$mzmed <- round(features$mzmed, 4)
features$rtmed <- round(features$rtmed)
```

## Specific features of blank samples (IS)

```{r}
features <- features[order(features$rtmed),]
idx <- features$npeaks == 2 & features$blank == 2
features$blank_prop <- features$mean_blank / features$mean_blank_no
features$blank_prop[features$blank_prop == "Inf"] <- features$mean_blank[features$blank_prop == "Inf"]
features$blank_prop <- round(features$blank_prop)
DT::datatable(features[
  idx, c("mzmed", "rtmed", "C", "compound", "annotation", "ppm", "RT_d", "blank_prop")])
```


### Duplicated identifications within blank samples (IS)

```{r}
idx <- features$npeaks == 2 & features$blank == 2 & !is.na(features$C) & 
  !grepl("Background", features$compound)
DT::datatable(features[
  (features$C == features$C[idx][duplicated(paste(features$C[idx], 
                                                  features$annotation[idx]))]) & 
    (features$annotation == features$annotation[idx][duplicated(paste(
      features$C[idx], features$annotation[idx]))]) & !is.na(features$C),
  c("mzmed", "rtmed", "C", "compound", "annotation", "ppm", "RT_d")])

if(z.polarity == "POS"){
  chr <- chromatogram(xdata, mz = 529.39855 + 0.01 * c(-1,1), rt = c(450, 550))
  plotChromPeakDensity(chr)
} else if(z.polarity == "NEG"){
  chr <- chromatogram(xdata, mz = 485.3367 + 0.01 * c(-1,1), rt = c(450, 550))
  plotChromPeakDensity(chr)
}
```


## Identifications of IS within STDmix samples

```{r}
idx <- features$npeaks == 2 & features$STDmix == 2 & !is.na(features$C)
DT::datatable(features[
  idx, c("mzmed", "rtmed", "C", "compound", "annotation", "ppm", "RT_d")])
```


## Others

```{r table-novale,eval=FALSE}
features <- features[order(features$compound),]
DT::datatable(
  features[!is.na(features$compound), 
           c("mzmed", "rtmed", "C", "compound", "annotation", "ppm", "RT_d", 
             "npeaks", "blank", "solv", "STDmix")])

features <- features[order(features$rtmed),]

View(features[features$npeaks == 2 & features$blank == 2, c("mzmed", "rtmed", "C", "compound", "annotation", "ppm", "RT_d")])
cmps$RTsec <- cmps$RT*60
table(features$rtmed[features$npeaks == 2 & features$blank == 2])
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```