---
title: "Feature grouping (STDmix), with functions"
output: html_document
---

**Modified**: `r file.info("IS_feature_grouping_v2.Rmd")$mtime`<br />
**Compiled**: `r date()`

```{r libraries, message=FALSE, warning=FALSE}
startpoint <- Sys.time()

library(xcms)
library(CluMSID)
library(CompoundDb)
library(Rdisop)
library(magrittr)
library(DT)

source("ft_grouping_functions.R")
```

```{r parameters}
mznoise <- c(158.975, 184.0731, 219.174, 221.154, 251.164, 267.196, 269.2115, 
             283.699, 415.284)


neutral_losses <- data.frame(
  formula = c("H2O", "C5H12NO5P", "C8H15NO4", "C9H17O10P", "C16H32O2", 
              "C19H38O4"),
  massdiff = NA
)
for(i in seq(nrow(neutral_losses))){
  neutral_losses$massdiff[i] <- getMolecule(neutral_losses$formula[i])$exactmass
}


massneg <- c(-1.007276, getMolecule("Cl")$exactmass, 
             c(-1.007276 + getMolecule("HCOOH")$exactmass))
names(massneg) <- c("[M-H]-", "[M+Cl]-", "[M-H+HCOOH]-")
masspos <- c(1.007276, getMolecule("NH4")$exactmass, getMolecule("Na")$exactmass,
             getMolecule("K")$exactmass, getMolecule("C2H8N")$exactmass)
names(masspos) <- c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", "[M+C2H8N]+")
massdif <- outer(masspos, massneg, "-")
colnames(massdif) <- names(massneg)
rownames(massdif) <- names(masspos) 


ann <- c(
  "[M+H]+", "13C[M+H]+", "(2)13C[M+H]+", "[M]+",
  "[M+NH4]+", "13C[M+NH4]+", "(2)13C[M+NH4]+", "[M]+ +NH3",
  "[M+Na]+", "13C[M+Na]+", "[M+K]+", 
  "[M+C2H8N]+", "13C[M+C2H8N]+",
  "[2M+H]+", "13C[2M+H]+", "(2)13C[2M+H]+", "[3M+H]+", "13C[3M+H]+",
  "[2M+Na]+", "13C[2M+Na]+",
  
  "[M-H]-", "13C[M-H]-", "(2)13C[M-H]-", "(3)13C[M-H]-",
  "[M-H+HCOOH]-", "13C[M-H+HCOOH]-", 
  "[2M-H]-", "13C[2M-H]-", "(2)13C[2M-H]-", "(3)13C[2M-H]-",
  "[2M-2H+Na]-",
  "[3M-H]-"
)
```


```{r code, message=FALSE}
startpointx <- Sys.time()
datax_pos <- ft_grouping(datax = dt_preparation(polarity = "POS"))
Sys.time()-startpointx

startpointx <- Sys.time()
datax_neg <- ft_grouping(datax = dt_preparation(polarity = "NEG"))
Sys.time()-startpointx


features <- isotopologues(rbind(datax_pos[["features"]], 
                                datax_neg[["features"]]))

data <- datax_pos[["data"]]
colnames(data) <- substring(colnames(data), 25, 39)
data_pos <- data[, order(colnames(data))]
data <- datax_neg[["data"]]
colnames(data) <- substring(colnames(data), 25, 39)
data_neg <- data[, order(colnames(data))]
data <- rbind(data_pos, data_neg)

features <- fg_grouping(data = data,
                        features = features)

startpointx <- Sys.time()
dt_ids <- identification(features)
Sys.time()-startpointx


datatable(dt_ids[, c(1:5,9)], rownames = FALSE,  
          options = list(dom = 't', pageLength = nrow(dt_ids))) %>% 
  formatStyle("color", target = "row", 
              backgroundColor = styleEqual(
                c(0, 1, 2, 3), c('', 'lightblue', '#C0819E60', 'lightgreen')))

Sys.time()-startpoint
```

