---
title: "MS2 Spectra"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

```{r, message=FALSE, warning=FALSE}
library(Spectra)
for(s in c("tissues", "maturation")){
  for(p in c("NEG", "POS")){
    fls <- list.files(paste0("data/", s, "/", p, "_DDA_mzML/"), 
                      full.names = TRUE)
    ms2 <- Spectra(fls, backend = MsBackendDataFrame())
    ms2 <- ms2[msLevel(ms2) == 2]
    mz_max <- rep(NA, length(ms2))
    intensity_max <- rep(NA, length(ms2))
    for(i in 1:length(ms2)){
      dt <- cbind(unlist(mz(ms2[i])), unlist(intensity(ms2[i])))
      idx <- which.max(dt[,2])
      mz_max[i] <- dt[idx, 1]
      intensity_max[i] <- dt[idx, 2]
    }
    ms2$mz_max <- mz_max
    ms2$intensity_max <- intensity_max
    save(ms2, file = paste0("data/RData/MS2_", s, "_", p, ".RData"))
  }
}
```



# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```