---
title: "Processing"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
p <- "NEG" # specify "POS" or "NEG"
s <- "tissues" # specify "maturation" or "tissues"

if(p == "NEG"){
  int <- 5e5
} else if(p == "POS"){
  int <- 5e6
}

if(s == "maturation"){
  v.class <- "type"
} else if(s == "tissues"){
  v.class <- "tissue"
}
```


## Libraries

```{r libraries, message = FALSE, warning = FALSE}
library(xcms)
library(Spectra)
library(tidyverse)
library(OrgMassSpecR)
library(Rdisop)
library(MetaboAnnotation)
library(MetaboCoreUtils)

.ppm <- function(x, ppm = 10) {
  ppm * x / 1e6
}
matchWithPpm <- function(x, y, ppm = 0) {
  lapply(x, function(z, ppm) {
    which(abs(z - y) <= (.ppm(z, ppm)) + 1e-9)
  }, ppm = force(ppm))
}
myimputer <- function(v){
  set.seed(123)
  if (sum(is.na(v)) == 0) {
    return(v)
  } else {
    napos <- which(is.na(v))
    if(min(v, na.rm = TRUE) > 2){
      newval <- runif(length(napos), 1, min(v, na.rm = TRUE)/10)
    } else {
      newval <- runif(length(napos), 0, min(v, na.rm = TRUE)/10)
    }
    out <- v
    out[napos] <- newval
    return(out)
  }
}
```


# MS-1

## Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", s, "/", p, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
if(s == "maturation"){
  colnames(tmp) <- c("order", "project", "pt", "time", "type", "rep", 
                     "p", "mode")
  tmp$mode[tmp$p == "FS"] <- tmp$p[tmp$p == "FS"] 
  tmp$p[tmp$p == "FS"] <- tmp$rep[tmp$p == "FS"] 
  tmp$p[tmp$p == "FS"] <- tmp$rep[tmp$p == "FS"] 
  tmp$rep[tmp$rep == p] <- tmp$type[tmp$rep == p] 
  idx <- tmp$time %in% c("solveq", "blank", "STDmix")
  tmp$type[idx] <- tmp$time[idx]
  tmp$time[idx] <- 0
  idx <- grep("QC", tmp$pt)
  tmp$type[idx] <- paste(tmp$pt[idx], tmp$time[idx], sep = "_")
  tmp$pt[idx] <- "xx"
  tmp$time[idx] <- 0
  tmp$type[tmp$type == "Rep" | tmp$type == "MIX"] <- "s"
} else if(s == "tissues"){
  tmp$X2 <- paste(tmp$X2, tmp$X3, sep = "_")
  tmp <- tmp[,-3]
  colnames(tmp) <- c("order", "project", "pt", "tissue", "rep", "p", "mode")
  tmp$tissue[grep("QC", tmp$pt)] <- paste(tmp$pt[grep("QC", tmp$pt)], 
                                          tmp$tissue[grep("QC", tmp$pt)], sep = "_")
  tmp$pt[grep("QC", tmp$pt)] <- "xx00"
}

injections <- cbind(injections, tmp)
rm(tmp)

if(s == "maturation"){
  injections <- injections[grep("slv_01", injections$filename):nrow(injections),]
  injections <- injections[grepl("Pt", injections$filename), ]
  injections$type <- paste0(injections$pt, injections$time)
  injections <- injections[!grepl("MIX", injections$filename), ]
} else if(s == "tissues"){
  injections <- injections[grep("solv_rep1", injections$filename):nrow(injections),]
  injections <- injections[grepl("skin|pulp|seeds", injections$tissue),]
}

# Read the data
data_raw <- readMSData(
  paste0("data/", s, "/", p, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


## Peak detection

```{r peak-detection}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, int),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)
```


### Filter low-intensity peaks

```{r filter-intensity}
xdata <- refineChromPeaks(xdata, 
                          param = FilterIntensityParam(
                            nValues = 5, threshold = int)
)
```

## Aligment

```{r aligment}
# Define the hook peaks
pdp <- PeakDensityParam(sampleGroups = pData(xdata)[,v.class],
                        minFraction = 1,
                        binSize = 0.02,
                        bw = 3)
xdata <- groupChromPeaks(xdata, param = pdp)

# Perform the aligment
pgp <- PeakGroupsParam(smooth = "loess",
                       span = 0.3,
                       minFraction = 1)
xdata <- adjustRtime(xdata, param = pgp)
```



## Correspondance

```{r correspondance}
xdata <- groupChromPeaks(xdata, param = pdp)
```


## Peak filling

```{r peak-filling}
fcp <- ChromPeakAreaParam()
xdata <- fillChromPeaks(xdata, param = fcp)
dim(featureDefinitions(xdata))
```


# MS-2

```{r ms2-import}
load(paste0("data/RData/MS2_", s, "_", p, ".RData"))
ms2 <- ms2[!grepl("STDmix", basename(ms2@backend@spectraData$dataOrigin))]
length(ms2)

# Exclude manually flagged MS2 spectras:
ms2_excl <- readxl::read_xlsx("MS2_exclude.xlsx")
int <- formatC(int, format = "e", digits = 1)
intx <- as.numeric(paste0(substr(
  as.character(int), 1, nchar(as.character(int))-1), 
  as.numeric(substr(as.character(int), nchar(as.character(int)), 
                    nchar(as.character(int))))-1))
ms2_excl <- ms2_excl[ms2_excl$counts > intx, ]
ms2_excl <- ms2_excl[ms2_excl$polarity == p, ]
ms2_excl <- ms2_excl[ms2_excl$study == s, ]
if(nrow(ms2_excl) > 0){
  noise <- c()
  for(i in seq(nrow(ms2_excl))){
    noise <- c(noise,  which(
      basename(ms2@backend@spectraData$dataOrigin) == ms2_excl$File[i] & 
        ms2@backend@spectraData$scanIndex == ms2_excl$scan[i]))
  }
  ms2 <- ms2[-noise]
  length(ms2)
}
```

## Flag low-quality spectra

```{r ms2-flag}
### Spectra whose MZ of main fragment > precursor
table(ms2$mz_max > precursorMz(ms2))

### There should be at least 1 fragment with an absolute intensity >100.000 counts
table(precursorIntensity(ms2) > as.numeric(int), ms2$intensity_max > intx)

ms2$good <- FALSE
ms2$good[ms2$mz_max < precursorMz(ms2) &
           precursorIntensity(ms2) > as.numeric(int) &
           ms2$intensity_max > intx] <- TRUE
table(ms2$good)
ms2 <- ms2[ms2$good]
```


# MS-1 & MS-2

```{r ms2-filter}
fls <- list.files(paste0("data/", s, "/", p, "_DDA_mzML/"))
ydata <- readMSData(paste0("data/", s, "/", p, "_DDA_mzML/" , fls), 
                    mode = "onDisk")
cwp@prefilter[2] <- intx
xchr <- findChromPeaks(ydata, param = cwp)
xchr <- refineChromPeaks(xchr, 
                         param = FilterIntensityParam(
                           nValues = 5, threshold = intx)
)
cp <- chromPeaks(xchr)
ft <- as.data.frame(featureDefinitions(xdata))
ft$ms2 <- NA
ms2$FT <- "X"
for(i in seq(nrow(ft))){
  idx_ms2 <- unlist(matchWithPpm(ft$mzmed[i], precursorMz(ms2), ppm = 10))
  if(s == "tissues" & p == "POS"){
    if(length(unlist(matchWithPpm(638.5718, ft$mzmed, ppm = 10))) > 1){
      rt <- round(ft$rtmed[unlist(matchWithPpm(638.5718, ft$mzmed, ppm = 10))])
      if(rt[which.max(rt)] == round(ft$rtmed[i])){
        idx_ms2 <- idx_ms2[- which(
          idx_ms2 == which(basename(
            ms2@backend@spectraData@listData$dataOrigin) ==
              "x008_lipidgrape_tissues_pt11_seeds_rep3_POS_DDA.mzML" & 
              ms2@backend@spectraData@listData$scanIndex == 2188))]
      }
    }
  }
  idx_cp <- unlist(matchWithPpm(ft$mzmed[i], cp[,"mz"], ppm = 10))
  cpx <- cp[idx_cp, ]
  if(length(idx_cp) > 1){
    idx_cp <- which(abs(cpx[,"rt"] - ft$rtmed[i]) < 10)
    cpx <- cpx[idx_cp, ]
  } else if(length(idx_cp) == 1){
    if(abs(cpx["rt"] - ft$rtmed[i]) > 10){
      idx_cp <- NULL
    }
  }
  if(length(idx_ms2) > 0){
    for(j in seq(length(idx_ms2))){
      idy <- which(basename(fileNames(ydata)) ==
                     basename(ms2@backend@spectraData$dataOrigin)[idx_ms2][j])
      if(length(idx_cp) == 1 & cpx["sample"] == idy){
        rtmin <- cpx["rtmin"]
        rtmax <- cpx["rtmax"]
      } else if(length(idx_cp) > 1){
        if(idy %in% cpx[,"sample"]) {
          rtmin <- min(cpx[cpx[,"sample"] == idy, "rtmin"])
          rtmax <- max(cpx[cpx[,"sample"] == idy, "rtmax"])
        } else {
          idx_cp <-NULL
        }
      }
      if((length(idx_cp) == 1 & cpx["sample"] == idy) |
         length(idx_cp) > 1){
        if((rtime(ms2)[idx_ms2][j] > rtmin) & (rtime(ms2)[idx_ms2][j] < rtmax)){
          ms2$FT[idx_ms2][j] <- gsub("X-", "", 
                                     paste(ms2$FT[idx_ms2][j], 
                                           rownames(ft)[i], sep = "-"))
          
        }
      }
    } # close idx "j"
  }
  ft$ms2[i] <- sum(grepl(rownames(ft)[i], ms2$FT))
}
table(ms2$FT != "X")
ms2 <- ms2[ms2$FT != "X"]
length(unique(unlist(strsplit(ms2$FT, "-"))))
ft <- ft[rownames(ft) %in% unique(unlist(strsplit(ms2$FT, "-"))),]
length(ms2)
sum(ft$ms2)

ft$ms2_sim <- NA
for(i in which(ft$ms2 > 1 & ft$ms2 < 10)){
  ms2sub <- ms2[grep(rownames(ft)[i], ms2$FT), ]
  mypairs <- t(combn(seq(length(ms2sub)), 2))
  pippo <- mypairs %>%
    as_tibble() %>% 
    mutate(mylist = map2(V1,V2, function(x,y) c(x,y))) %>% 
    pull(mylist)
  pluto <- lapply(pippo, function(x) {
    #list(ms2sub[x[1]], ms2sub[x[2]])
    list(cbind( "mz" = unlist(mz(ms2sub[x[1]])), 
                "intensity" = unlist(intensity(ms2sub[x[1]]))),
         cbind( "mz" = unlist(mz(ms2sub[x[2]])), 
                "intensity" = unlist(intensity(ms2sub[x[2]]))))
  }) 
  myf <- function(x){
    #Spectra::compareSpectra(x[[1]], x[[2]], ppm = 10)
    SpectrumSimilarity(x[[1]], x[[2]], print.graphic = FALSE, t = 0.005, b = 10)
  }
  if(length(ms2sub) == 1){
    ft$ms2_sim[i] <- "-"
  } else if(length(ms2sub) == 2){
    ft$ms2_sim[i] <- sprintf("%.3f", unlist(lapply(pluto, myf)))
  } else {
    ft$ms2_sim[i] <- paste(sprintf(
      "%.3f", range(unlist(lapply(pluto, myf)))), collapse = "-")
  }
}
```


# Identification

```{r identification}
db_exp <- tibble(
  FT = rownames(ft),
  precursor = ft[, "mzmed"],
  rtime = ft[, "rtmed"],
  MS2_n = ft[,"ms2"],
  MS2_sim = ft[,"ms2_sim"]
)

cmps <- read.csv("compounds.csv")
cmps <- cmps[!cmps$compound %in% c(
  "FFA(22:0)", "PA(18:1/18:3)", "PC(18:1/18:3)", 
  "PE(18:1/18:1)", "PE(18:1/18:3)"),]
cmps$exactmass <- NA
for(i in seq(nrow(cmps))){
  if(grepl("D", cmps$formula[i])){
    cmps$exactmass[i] <- getMolecule(cmps$formula[i])$exactmass
  }else if(grepl("C", cmps$formula[i])){
    cmps$exactmass[i] <- MonoisotopicMass(formula = ListFormula(
      cmps$formula[i])) 
  } else {
    cmps$exactmass[i] <- as.numeric(cmps$formula[i])
  }
}
cmps$rtime <- cmps$rtime*60

adds <- data.frame(rbind(
  c("[M-H]-",            -1.007276,              1, "NEG"), 
  c("13C[M-H]-",         -1.007276 + 1.003355,   1, "NEG"), 
  c("(2)13C[M-H]-",      -1.007276 + 1.003355*2, 1, "NEG"), 
  c("[M-H+HCOOH]-",      44.998200,              1, "NEG"),
  c("13C[M-H+HCOOH]-",   44.998200 + 1.003355,   1, "NEG"),
  c("(2)13C[M-H+HCOOH]-",44.998200 + 1.003355*2, 1, "NEG"),  
  c("[2M-H]-",           -1.007276,              2, "NEG"),
  c("[2M+Na-2H]-",       20.974668,              2, "NEG"), 
  c("13C[2M+Na-2H]-",    20.974668 + 1.003355,   2, "NEG"), 
  c("[M-H-H2O]-",       -1.007276 - 18.0105647,  1, "NEG"), 
  c("[M-CH3]-",         -15.023475105,           1, "NEG"),
  c("[14:3-H]-",        -219.174076,             1, "NEG"),
  
  c("[M+H]+",             1.007276,              1, "POS"), 
  c("13C[M+H]+",          1.007276 + 1.003355,   1, "POS"), 
  c("(2)13C[M+H]+",       1.007276 + 1.003355*2, 1, "POS"), 
  c("[M+NH4]+",          18.033830,              1, "POS"),
  c("13C[M+NH4]+",       18.033830 + 1.003355,   1, "POS"),
  c("(2)13C[M+NH4]+",    18.033830 + 1.003355*2, 1, "POS"),
  c("[M+C2H8N]+",        46.065674,              1, "POS"),
  c("13C[M+C2H8N]+",     46.065674 + 1.003355,   1, "POS")
))
colnames(adds) <- c("name", "mass_add", "mass_multi", "p")
rownames(adds) <- adds$name
adds$mass_add <- as.numeric(adds$mass_add)
adds$mass_multi <- as.numeric(adds$mass_multi)

parm <- Mass2MzRtParam(adducts = adds[adds$p == p, ], 
                       ppm = 10, toleranceRt = 10)
ft_match <- matchMz(as.data.frame(db_exp), cmps, parm, 
                    mzColname = "precursor", rtColname = "rtime")
ft_match_out <- as.data.frame(matchedData(ft_match))
tmp <- ft_match_out[!is.na(ft_match_out$target_compound), ]
tmp2 <- gsub("\\..*", "", rownames(tmp))
if(any(duplicated(tmp2))){
  dpl <- unique(tmp2[duplicated(tmp2)])
  for(i in unique(dpl)){
    i.tmp <- tmp[gsub("\\..*", "", rownames(tmp)) == i, ]
    idx <- which(rownames(tmp)  == i)
    i.tmp <- i.tmp[!grepl("\\(2)13C", i.tmp$adduct),]
    if(nrow(i.tmp) > 1){
      i.tmp <- i.tmp[!grepl("CH3", i.tmp$adduct),]
      i.tmp <- i.tmp[!grepl("C2H8N", i.tmp$adduct),]
    } else if(nrow(i.tmp) == 0){
      i.tmp <- tmp[gsub("\\..*", "", rownames(tmp)) == i, ]
    }
    i.tmp <- i.tmp[which.min(abs(i.tmp$rtime - i.tmp$target_rtime)),]
    ft_match_out[idx,] <- i.tmp
  }
}
if(any(grep("\\.", rownames(ft_match_out)))){
  ft_match_out <- ft_match_out[-grep("\\.", rownames(ft_match_out)),]
}
db_exp$compound <- ft_match_out$target_compound
db_exp$adduct <- ft_match_out$adduct
table(!is.na(db_exp$compound))
length(unique(db_exp$compound[!is.na(db_exp$compound)]))
```


## Fragmentation patterns

```{r fragmentation}
ids <- c()

C <- seq(from = 16, to = 18, by = 2)
db <- seq(from = 0, to = 3, by = 1)
sn <-  paste(expand.grid(C, db)[,"Var1"], expand.grid(C, db)[,"Var2"], 
             sep = ":")

cls <- c("PA", "mPA", "PC", "PE", "PG", "PI", "PS", 
         "CER", "CER-FA", "CERhex", "CERhex-FA", 
         "MGDG", "MGDG-Na", "DGDG", "DGDG-Na", 
         "DAG")
for(i in cls){
  ids <- c(ids, paste(i, expand.grid(sn, sn)[,"Var1"], 
                      expand.grid(sn, sn)[,"Var2"], sep = "_"))
}

cls <- "TAG"
sn <-  paste(expand.grid(C, db)[,"Var1"], expand.grid(C, db)[,"Var2"], sep = ":")
for(i in cls){
  ids <- c(ids, paste(i, expand.grid(sn, sn, sn)[,"Var1"], 
                      expand.grid(sn, sn, sn)[,"Var2"], 
                      expand.grid(sn, sn, sn)[,"Var3"], sep = "_"))
}


source("formula_generator.R")
source("ms2patterns_stds_neg.R")
source("ms2patterns_stds_pos.R")
source("ms2patterns_samples_neg.R")
source("ms2patterns_samples_pos.R")

db_thr <- tibble(id = ids) %>% 
  mutate(class = map_chr(id, function(x){unlist(strsplit(x, "_"))[1]})) %>%
  mutate(sn = map(id, function(x){unlist(strsplit(x, "_"))[-1]})) %>%
  mutate(C = map_dbl(sn, function(x){sum(as.numeric(gsub(":.*", "", x)))})) %>%
  mutate(db = map_dbl(sn, function(x){sum(as.numeric(gsub(".*:", "", x)))})) %>% 
  mutate(id2 = paste0(class, C, ":", db)) %>%
  mutate(formula = pmap_chr(list(class = class, C = C, db = db), 
                            function(class, C, db){
                              fml_maker(class, C, db)})) %>%
  mutate(neg_precursor = pmap_dbl(list(class = class, formula = formula),
                                  function(class = class, formula = formula){
                                    precursor_neg(class, formula)})) %>%
  mutate(neg_ms2_std = pmap(list(class = class, formula = formula, sn = sn),
                            function(class = class, formula = formula, sn = sn){
                              ms2_neg_std(class, formula, sn)
                            })) %>%
  mutate(neg_ms2_smp = pmap(list(class = class, formula = formula, sn = sn),
                            function(class = class, formula = formula, sn = sn){
                              ms2_neg_smp(class, formula, sn)
                            }))  %>%
  mutate(pos_precursor = pmap_dbl(list(class = class, formula = formula),
                                  function(class = class, formula = formula){
                                    precursor_pos(class, formula)})) %>%
  mutate(pos_ms2_std = pmap(list(class = class, formula = formula, sn = sn),
                            function(class = class, formula = formula, sn = sn){
                              ms2_pos_std(class, formula, sn)
                            }))%>%
  mutate(pos_ms2_smp = pmap(list(class = class, formula = formula, sn = sn),
                            function(class = class, formula = formula, sn = sn){
                              ms2_pos_smp(class, formula, sn)
                            }))



db_exp$compound <- gsub(")", "", db_exp$compound)
db_exp$compound <- gsub("\\(", "_", db_exp$compound)
db_exp$compound <- gsub("/", "_", db_exp$compound)

ms2sim_std <- function(compound, precursor, FT){
  idx <- which(db_thr$id %in% unlist(strsplit(compound, " - ")))
  idx <- idx[unlist(matchWithPpm(
    precursor, 
    db_thr[idx, paste0(tolower(p), "_precursor")], ppm = 10))]
  if(length(idx) > 0){
    ms2sub <- ms2[grep(FT, ms2$FT)]
    ms2sub <- Spectra::combineSpectra(
      ms2sub, intensityFun = base::sum, mzFun = base::mean, 
      tolerance = 0.005, minProp = 0.5, peaks = "intersect", 
      weighted = TRUE)
    if(length(idx) == 1){
      sim <- SpectrumSimilarity(
        cbind("mz" = unlist(mz(ms2sub)),
              "intensity" = unlist(intensity(ms2sub))), 
        db_thr[[idx,paste0(tolower(p), "_ms2_std")]][[1]], 
        print.graphic = FALSE, t = 0.005, b = 10)
    } else if(length(idx) > 1){
      sim <- list()
      for(k in seq(length(idx))){
        sim[[k]] <- SpectrumSimilarity(
          cbind("mz" = unlist(mz(ms2sub)),
                "intensity" = unlist(intensity(ms2sub))), 
          db_thr[[idx[k],paste0(tolower(p), "_ms2_std")]][[1]], 
          print.graphic = FALSE, t = 0.005, b = 10)
        names(sim)[k] <- db_thr$id[idx[k]]
      }
    }
  }else{
    sim <- 0
  }
  sim
}

ms2sim_smp <- function(compound, precursor, FT){
  idx <- which(db_thr$id %in% unlist(strsplit(compound, " - ")))
  idx <- idx[unlist(matchWithPpm(
    precursor, 
    db_thr[idx, paste0(tolower(p), "_precursor")], ppm = 10))]
  if(length(idx) > 0){
    ms2sub <- ms2[grep(FT, ms2$FT)]
    ms2sub <- Spectra::combineSpectra(
      ms2sub, intensityFun = base::sum, mzFun = base::mean, 
      tolerance = 0.005, minProp = 0.5, peaks = "intersect", 
      weighted = TRUE)
    if(length(idx) == 1){
      sim <- SpectrumSimilarity(
        cbind("mz" = unlist(mz(ms2sub)),
              "intensity" = unlist(intensity(ms2sub))), 
        db_thr[[idx,paste0(tolower(p), "_ms2_smp")]][[1]], 
        print.graphic = FALSE, t = 0.005, b = 10)
    } else if(length(idx) > 1){
      sim <- list()
      for(k in seq(length(idx))){
        sim[[k]] <- SpectrumSimilarity(
          cbind("mz" = unlist(mz(ms2sub)),
                "intensity" = unlist(intensity(ms2sub))), 
          db_thr[[idx[k],paste0(tolower(p), "_ms2_smp")]][[1]], 
          print.graphic = FALSE, t = 0.005, b = 10)
        names(sim)[k] <- db_thr$id[idx[k]]
      }
    }
  }else{
    sim <- 0
  }
  sim
}

db_exp <- db_exp %>%
  filter(MS2_n > 0) %>%
  filter(!is.na(compound)) %>%
  mutate(sim_std = pmap(list(compound, precursor, FT),
                        function(compound, precursor, FT){
                          ms2sim_std(compound, precursor, FT)
                        })) %>%
  mutate(sim_smp = pmap(list(compound, precursor, FT),
                        function(compound, precursor, FT){
                          ms2sim_smp(compound, precursor, FT)
                        }))
length(unique(db_exp$compound))
unique(db_exp$compound)
```


# Feature grouping

```{r ft-group}
feats <- as.data.frame(featureDefinitions(xdata))
feats <- feats[rownames(feats) %in% db_exp$FT, ]
db_exp <- db_exp[order(db_exp$FT),]
all(rownames(feats) == db_exp$FT)
db_exp$mean <- NA
for(i in seq(nrow(feats))){
  db_exp$mean[i] <- mean(chromPeaks(xdata)[unlist(feats$peakidx[i]),"into"])
}
db_exp <- db_exp[order(db_exp$mean, decreasing = TRUE),]
db_exp$precursor <- as.numeric(db_exp$precursor)
db_exp$rtime <- as.numeric(db_exp$rtime)
data <- as.data.frame(t(featureValues(xdata, method = "sum", value = "into")))
db_exp$FG <- NA
fgn <- 0
for(i in seq(nrow(db_exp))){
  if(is.na(db_exp$FG[i])){
    fgn <- fgn + 1
    ft <- db_exp[db_exp$rtime > (db_exp$rtime[i] - 10) & 
                   db_exp$rtime < (db_exp$rtime[i] + 10), ]
    ft <- ft[is.na(ft$FG), ]
    if(nrow(ft) > 1){
      dt <- data[,colnames(data) %in% ft$FT]
      dt <- apply(dt, 2, myimputer)
      cori <- cor(log10(dt[,db_exp$FT[i]]), log10(dt))
      if(length(which(cori > 0.7)) > 1){
        dt <- dt[,cori > 0.7]
        ft <- ft[ft$FT %in% colnames(dt), ]
        chr <- chromatogram(xdata, 
                            mz = db_exp$precursor[i] + 0.01 * c(-1, 1), 
                            rt = db_exp$rtime[i] + 15 * c(-1, 1),
                            aggregationFun = "max")
        chrcor <- rep(NA, nrow(ft))
        for(j in seq(nrow(ft))){
          chrj <- chromatogram(xdata, 
                               mz = ft$precursor[j] + 0.01 * c(-1, 1), 
                               rt = ft$rtime[j] + 15 * c(-1, 1),
                               aggregationFun = "max")
          chrcorx <- rep(NA, length(chr))
          for(k in seq(length(chr))){
            chrcorx[k] <- correlate(chr[[k]], chrj[[k]])
          }
          chrcor[j] <- mean(chrcorx)
          names(chrcor)[j] <- ft$FT[j]
        }
        chrcor[is.na(chrcor)] <- 0
        if(length(which(chrcor > 0.9)) > 1){
          ft <- ft[chrcor > 0.9, ]
          db_exp$FG[db_exp$FT %in% ft$FT] <- fgn
        } else {
          db_exp$FG[i] <- fgn
        }
      } else {
        db_exp$FG[i] <- fgn
      }
    }else {
      db_exp$FG[i] <- fgn
    }
  }
}
for(i in unique(db_exp$FG)){
  if(length(unique(db_exp$compound[db_exp$FG == i])) > 1){
    print(i)
    print(db_exp[db_exp$FG == i, c("precursor", "compound", "adduct", "FG")])
    print("------------------------------------------------------")
  }
}
for(i in unique(db_exp$compound)){
  if(length(unique(db_exp$FG[db_exp$compound == i])) > 1){
    print(i)
    print(db_exp[db_exp$compound == i, c("precursor", "compound", "adduct", "FG")])
    print("------------------------------------------------------")
  }
}
```


# Output

```{r output}
db_exp$precursor <- sprintf("%.4f", db_exp$precursor)
db_exp$rtime <- sprintf("%.2f", db_exp$rtime/60)
db_exp$sim_std <- sprintf("%.3f", db_exp$sim_std)
db_exp$sim_smp <- sprintf("%.3f", db_exp$sim_smp)
db_exp <- db_exp[order(db_exp$compound),]
cmp <- db_exp$compound[!grepl("13C", db_exp$adduct)]
```

## Main

```{r}
idx <- db_exp$compound %in% cmp
DT::datatable(db_exp[idx,], rownames = FALSE, options = list(
  pageLength = sum(idx), dom = "t"))
```

## Others

```{r}
DT::datatable(db_exp[!idx,], rownames = FALSE, options = list(
  pageLength = sum(!idx), dom = "t"))
```


# MS2 to exclude to pseudo-manually flag

```{r ms2-to-flag}
ms2_excl <- readxl::read_xlsx("MS2_exclude.xlsx")
ms2_excl <- ms2_excl[ms2_excl$polarity == p & ms2_excl$study == s, ]
todo <- paste(db_exp$compound, db_exp$adduct)
todo <- todo[!grepl("13C", todo)]
if(nrow(ms2_excl) > 0){
  excl <- unique(paste(ms2_excl$compound, ms2_excl$adduct))
  if(s == "tissues" & p == "NEG"){
    excl <- c(
      excl, 
      "PA_16:0_18:1 [M-H]-", "PA_16:0_18:2 [2M-H]-", "PA_18:1_18:2 [M-H]-", 
      "PA_18:2_18:2 [M-H]-", "PA_18:3_18:3 [M-H]-",
      "mPA_16:0_18:1 [M-H]-", "mPA_16:0_18:2 [M-H]-", 
      "mPA_18:0_18:1 [M-H]-", "mPA_18:1_18:2 [M-H]-", "mPA_18:2_18:3 [M-H]-",
      "dmPA_16:0_18:1 [M-H]-", "dmPA_16:0_18:2 [M-H]-", "dmPA_18:2_18:2 [M-H]-", 
      "PC_15:0_18:1d7 [M-H+HCOOH]-",
      "PE_15:0_18:1d7 [M-H]-", "PE_16:0_18:1 _II [M-H]-", "PE_18:2_18:2 [M-H]-", 
      "PG_15:0_18:1d7 [M-H]-", "PG_16:0_16:0 [M-H]-", "PG_16:0_18:1 [M-H]-", 
      "PG_16:0_18:2 [M-H]-",
      "FFA_32:4 [M-H+HCOOH]-", "FFA_PA_20:0 [M-H]-", 
      "FFA_red_21:1 [M-H+HCOOH]-", "FFA_red_22:1 [M-H+HCOOH]-", "FFA_red_23:1 [M-H+HCOOH]-",
      "CER_dihydroxy_16:0_26:1 [M-H]-", 
      "CER_dihydroxy_18:0_22:0 [M-H]-", "CER_dihydroxy_18:0_22:0 [M-H+HCOOH]-",
      "CER_dihydroxy_18:0_24:0 [M-H]-","CER_dihydroxy_41:1 [M-H+HCOOH]-",
      "CER_hex_hydroxy_34:1 [M-H+HCOOH]-", "CER_hex_hydroxy_34:1 [M-H]-",
      "CER_hex_hydroxy_34:2 [M-H+HCOOH]-", "CER_hex_hydroxy_34:2 [M-H]-",
      "CER_hex_dihydroxy_16:0_18:1 [M-H]-", "CER_hex_dihydroxy_18:1_22:0 [M-H]-",
      "CER_hex_dihydroxy_18:1_23:0 [M-H]-", "CER_hex_dihydroxy_18:1_24:0 [M-H]-", 
      "CER_hex_dihydroxy_18:1_26:0 [M-H]-", 
      "MGDG_18:1_18:2 [M-H+HCOOH]-", "MGDG_18:2_18:2 [M-H+HCOOH]-",
      "Malic acid [M-H]-",
      "Unk-075 _14:2_15:3 [M-H]-", "Unk-173 [M-H+HCOOH]-", 
      "Unk-202 _18:2_20:0 [M-H]-", "Unk-270 _16:0_18:2 [M-H]-")
  } else if(s == "maturation" & p == "NEG"){
    excl <- c(
      excl, 
      "PA_16:0_18:1 [M-H]-", "PA_18:1_18:2 [M-H]-",
      "mPA_16:0_18:2 [M-H]-", "mPA_16:0_18:3 [M-H]-",
      "mPA_18:2_18:2 [M-H]-", "mPA_18:2_18:3 [M-H]-",
      "LPC_18:1d7 [M-H+HCOOH]-", "LPE_18:1d7 [M-H]-",
      "PE_16:0_18:3 [M-H]-", 
      "PE_18:0_18:3[M-H]-", "PE_18:1_18:2 [M-H]-", "PE_18:2_18:2 [M-H]-", "PE_18:3_18:2 [M-H]-", 
      "PE_20:0_18:2 [M-H]-", "PE_22:0_18:2 [M-H]-",
      "PG_16:0_16:0 [M-H]-","PG_16:0_18:1 [M-H]-",
      "PI_16:0_18:1 [M-H]-",
      "CER_hex_dihydroxy_18:1_22:0 [M-H]-", "CER_hex_dihydroxy_18:1_24:0 [M-H]-")
  } else if(s == "tissues" & p == "POS"){
    excl <- c(
      excl, 
      "LPC_16:0 [M+H]+",
      "PE_18:1_18:2 [M+H]+", "PE_18:2_18:2 [M+H]+",
      "CER_dihydroxy_16:0_26:1 [M+H]+",
      "DAG_18:2_18:3 [M+NH4]+", "DAG_18:2_20:0 [M+NH4]+", 
      "TAG_16:0_16:0_16:0 [M+NH4]+", "TAG_16:0_16:2_18:3 [M+NH4]+", 
      "TAG_18:3_18:3_20:0 [M+NH4]+",
      "Unk-010 _I [M+C2H8N]+")
  }else if(s == "maturation" & p == "POS"){
    excl <- c(
      excl, "PE_16:0_18:2 _I [M+H]+")
  }
  todo <- todo[!todo %in% excl]
} 
idx <- which(paste(db_exp$compound, db_exp$adduct) %in% todo)
DT::datatable(db_exp[idx, ], rownames = FALSE, options = list(
  pageLength = length(idx), dom = "t"))
```

# Save data

```{r save}
save(xdata, ms2, db_exp, 
     file = paste0("data/RData/data_", s, "_", p, ".RData"))
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```

