---
title: "Quantification"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

# Main code

## Libraries

```{r libraries, message=FALSE, warning=FALSE}
library(xcms)
library(MetaboCoreUtils)
library(Rdisop)
.ppm <- function(x, ppm = 10) {
  ppm * x / 1e6
}
matchWithPpm <- function(x, y, ppm = 0) {
  lapply(x, function(z, ppm) {
    which(abs(z - y) <= (.ppm(z, ppm)) + 1e-9)
  }, ppm = force(ppm))
}
```

## Data import

```{r import}
cmps <- read.csv("compounds.csv")
res <- read.csv("output/res.csv")
res$id <- res$name_old
res$id <- gsub(")", "", res$id)
res$id <- gsub("\\(", "_", res$id)
res$id <- gsub("/", "_", res$id)

for(s in c("tissues", "maturation")){
  if(!dir.exists(paste0("output/chr_", s))){
    dir.create(paste0("output/chr_", s))
  }
  for(p in c("POS", "NEG")){
    load(paste0("data/RData/data_", s, "_", p, ".RData"))
    cmp <- unique(db_exp$compound[!grepl("13C", db_exp$adduct)])
    db_exp <- db_exp[db_exp$compound %in% cmp, ]
    db_exp$polarity <- p
    db_exp$study <- s
    assign(paste0("dbexp_", p), db_exp)
    feat <- as.data.frame(featureDefinitions(xdata))
    assign(paste0("feat_", s, "_", p), feat)
    ydata <- list.files(paste0("data/", s, "/", p, "_FS_fixed/"))
    if(s == "tissues"){
      ydata <- ydata[grep(paste(c("seeds", "pulp", "skin", "entire", 
                                  "QC", "solv"), 
                                collapse = "|"), ydata)]
    } else if(s == "maturation"){
      ydata <- ydata[grep(paste(c("Pt", "QC", "slv"), 
                                collapse = "|"), ydata)]
      ydata <- ydata[!grepl(("MIX"), ydata)]
    }
    ydata <- ydata[!grepl("QCeq|solveq", ydata)]
    ydata <- readMSData(paste0("data/", s, "/", p, "_FS_fixed/", ydata), 
                        mode = "onDisk")
    assign(paste0("ydata_", s, "_", p), ydata)
    
    cwp <- processParam(processHistory(xdata)[[1]])
    int <- cwp@prefilter[2]
    intx <- as.numeric(paste0(substr(
      as.character(int), 1, nchar(as.character(int))-1), 
      as.numeric(substr(as.character(int), nchar(as.character(int)), 
                        nchar(as.character(int))))-1))
    cwp@prefilter[2] <- intx
    xchr <- findChromPeaks(ydata, param = cwp)
    cp <- chromPeaks(xchr)
    assign(paste0("cp_", s, "_", p), cp)
    assign(paste0("xdata_", s, "_", p), xdata)
    
    col_smpl <- rep("grey", length(fileNames(ydata)))
    col_smpl[grep("skin", fileNames(ydata))] <- "#377EB8"
    col_smpl[grep("pulp", fileNames(ydata))] <- "#4DAF4A"
    col_smpl[grep("seeds", fileNames(ydata))] <- "#984EA3"
    col_smpl[grep("entire", fileNames(ydata))] <- "#A65628"
    col_smpl[grep("solv", fileNames(ydata))] <- "black"
    col_smpl[grep("QCdl_02uL", fileNames(ydata))] <- "#FFFFB2"
    col_smpl[grep("QCdl_05uL", fileNames(ydata))] <- "#FED976"
    col_smpl[grep("QCdl_10uL", fileNames(ydata))] <- "#FEB24C"
    col_smpl[grep("QCrw_02uL", fileNames(ydata))] <- "#FD8D3C"
    col_smpl[grep("QCrw_05uL", fileNames(ydata))] <- "#F03B20"
    col_smpl[grep("QCrw_10uL", fileNames(ydata))] <- "#BD0026"
    col_smpl[grep("Pt_01", fileNames(ydata))] <- "#EFF3FF"
    col_smpl[grep("Pt_02", fileNames(ydata))] <- "#C6DBEF"
    col_smpl[grep("Pt_03", fileNames(ydata))] <- "#9ECAE1"
    col_smpl[grep("Pt_04", fileNames(ydata))] <- "#6BAED6"
    col_smpl[grep("Pt_05", fileNames(ydata))] <- "#4292C6"
    col_smpl[grep("Pt_06", fileNames(ydata))] <- "#2171B5"
    col_smpl[grep("Pt_07", fileNames(ydata))] <- "#084594"
    col_smpl[grep("Pt_08", fileNames(ydata))] <- "#9E9AC8"
    col_smpl[grep("Pt_09", fileNames(ydata))] <- "#807DBA"
    col_smpl[grep("Pt_10", fileNames(ydata))] <- "#6A51A3"
    col_smpl[grep("Pt_11", fileNames(ydata))] <- "#54278F"
    col_smpl[grep("Pt_12", fileNames(ydata))] <- "#3F007D"
    col_smpl[grep("Pt_13", fileNames(ydata))] <- "#3F007D"
    col_smpl[grep("slv", fileNames(ydata))] <- "black"
    assign(paste0("col_", s, "_", p), col_smpl)
  }
  
  dbexp <- rbind(dbexp_NEG, dbexp_POS)
  assign(paste0("dbexp_", s), dbexp)
  
  data <- matrix(nrow = length(fileNames(ydata)), ncol = nrow(res))
  if(s == "tissues"){
    smpl <- unlist(substring(basename(fileNames(ydata)), 25, 40))
    smpl <- gsub("xx00_", "", smpl)
    smpl <- gsub("_N|_P|_NEG|_POS", "", smpl)
    idx <- grepl("_$", smpl)
    smpl[idx] <- unlist(substring(smpl[idx], 1, 15))
  } else if(s == "maturation"){
    smpl <- unlist(substring(basename(fileNames(ydata)), 17, 28))
    smpl <- gsub("xx_00_xQC_", "QC", smpl)
    smpl <- gsub("Rep_", "", smpl)
    smpl <- gsub("Pt_", "Pt", smpl)
  }
  rownames(data) <- smpl
  colnames(data) <- res$id
  assign(paste0("data_", s), data)
}
dbexp <- rbind(dbexp_tissues, dbexp_maturation)
dbexp <- dbexp[!grepl("13C", dbexp$adduct),]
rm(feat, ydata, ms2, xdata, smpl, col_smpl, data, 
   db_exp, dbexp_NEG, dbexp_POS, dbexp_tissues, dbexp_maturation)
```

## Peak integration

```{r peaks}
dbexp$adduct <- gsub("\\[M-H\\+HCOOH]-", "\\[M\\+CHO2]-", dbexp$adduct)
res$pw_t <- NA
res$pw_m <- NA
for(i in seq(nrow(res))){
  fml <- unique(cmps$formula[cmps$compound == res$name_old[i]])
  cl <- unique(cmps$class[cmps$compound == res$name_old[i]])
  if(cl %in% c(
    "FFA_PA", "CER_hex_dihydroxy", "PA", "mPA", "dmPA", "LPE", "PE",
    "LPG", "PG", "PI", "PS", "SQDG", "unk_B", "unk_C", "unk_D")){
    ad <- "[M-H]-"
    pol <- "NEG"
  } else if(cl %in% c(
    "CER", "CER_hydroxy", "CER_dihydroxy", "CER_hex_hydroxy", 
    "PC", "MGDG", "DGDG", "unk_A", "unk_E")){
    ad <- "[M+CHO2]-"
    pol <- "NEG"
  } else if(cl %in% c("CAR", "LPC")){
    ad <- "[M+H]+"
    pol <- "POS"
  } else if(cl %in% c("DAG", "TAG", "sitosterol")){
    ad <- "[M+NH4]+"
    pol <- "POS"
  } else if(res$name_old[i] %in% c(
    "(Epi)catechin", "Kaempferol glucoside", "Disaccharide", "Malic acid",
    "Unk-006 (pph_glucoside)", "Unk-029 (18:2)", 
    "Unk-021", "Unk-022", "Unk-023", "Unk-027","Unk-028",
    "Unk-031", "Unk-032", "Unk-033 (18:2)", "Unk-034", "Unk-037 (14:3)",
    "Unk-039", "Unk-042", "Unk-043 (15:3)", "Unk-044 (I)", "Unk-045 (I)",
    "Unk-061 (I)", "Unk-075 (14:2/15:3)",
    "Unk-174 (16:0)","Unk-175 (18:2)",
    "Unk-184 (glucoside)", "Unk-191 (16:0/18:1)", 
    "Unk-201", "Unk-202", "Unk-208", "Unk-211","Unk-213 (18:2)",
    "Unk-212", "Unk-222", "Unk-223", "Unk-224", "Unk-229 (I)", "Unk-229 (II)",
    "Unk-231", "Unk-232 (18:2)", "Unk-247", "Unk-250", "Unk-253", "Unk-266",
    "Unk-271")){
    ad <- "[M-H]-"
    pol <- "NEG"
  } else if(res$name_old[i] %in% c(
    "Unk-030", "Unk-068", "Unk-079", "Unk-173", "Unk-187", "Unk-198")){
    ad <- "[M+CHO2]-"
    pol <- "NEG"
  } else if(res$name_old[i] %in% c(
    "Unk-001 (I)", "Unk-001 (II)", "Unk-003", 
    "Unk-010 (I)", "Unk-010 (II)", "Unk-010 (III)", "Unk-010 (IV)", 
    "Unk-038 (I)", "Unk-038 (II)", "Unk-090",
    "Unk-168", "Unk-169 (18:3)", "Unk-170 (I)", "Unk-172 (18:3)",
    "Unk-176", "Unk-178 (16:0/18:0)", "Unk-193", "Unk-194", "Unk-200 (18:2/18:3)",
    "Unk-206 (16:0/18:2/18:3)", "Unk-207", "Unk-209", "Unk-210 (16:0)", "Unk-214",
    "Unk-234", "Unk-235", "Unk-236", "Unk-237", "Unk-238")){
    ad <- "[M+H]+"
    pol <- "POS"
  } else if(res$name_old[i] %in% c(
    "Unk-005", "Unk-025 (18:1/18:2)", "Unk-026 (II)", "Unk-026 (III)", 
    "Unk-040", "Unk-041 (18:2)", 
    "Unk-051 (18:0/18:1/18:2)", "Unk-059 (II)", 
    "Unk-062 (16:0/18:2) (I)", "Unk-089", "Unk-123", 
    "Unk-170 (II) (18:2)")){
    ad <- "[M+NH4]+"
    pol <- "POS"
  }
  # to do: Malic acid
  if(exists("ad")){
    for(s in c("tissues", "maturation")){
      ft <- dbexp$FT[dbexp$compound == res$id[i] & 
                       dbexp$study == s & dbexp$adduct == ad]
      xdata <- get(paste0("xdata_", s, "_", pol))
      if(grepl("C", fml)){
        mz <- mass2mz(getMolecule(fml)$exactmass, ad)
      } else{
        mz <- mass2mz(as.numeric(fml), ad)
      }
      ydata <- get(paste0("ydata_", s, "_", pol))
      if(length(ft) == 1){
        feat <- get(paste0("feat_", s, "_", pol))
        cp <- chromPeaks(xdata)[unlist(feat[ft, "peakidx"]),]
        rtmin <- min(cp[,"rtmin"])
        rtmax <- max(cp[,"rtmax"])
      } else {#if(length(ft) == 0){
        cp <- as.data.frame(get(paste0("cp_", s, "_", pol)))
        cpx <- cp[unlist(matchWithPpm(mz, cp$mz, ppm = 10)),]
        cpx <- cpx[(cpx$rtmin < res$RT[i]*60) & 
                     (cpx$rtmax > res$RT[i]*60),]
        if(any(duplicated(cpx$sample))){
          print(paste("Ull! Check", res$name_old[i], "in", s, 
                      "for duplicated cpx$sample!"))
        } else {
          rtmin <- min(cpx$rtmin)
          rtmax <- max(cpx$rtmax)
        }
      } #else {
      #print(paste("ULL! Check", res$name_old[i], "in", s))
      #rtmin <- min(cpx$rtmin)
      #rtmax <- max(cpx$rtmax)
      #}
      i.cmp <- matrix(c(as.numeric(mz) + 0.01 * c(-1, 1),
                        rtmin, rtmax), nrow = 1)
      colnames(i.cmp) <- c("mzmin", "mzmax", "rtmin", "rtmax")
      
      
      if(!is.na(cmps[cmps$compound == res$name_old[i], paste0(
        substr(s, 1, 1), "_min")])){
        i.cmp[,"rtmin"] <- cmps[cmps$compound == res$name_old[i], 
                                paste0(substr(s, 1, 1), "_min")]*60
      }
      if(!is.na(cmps[cmps$compound == res$name_old[i], paste0(
        substr(s, 1, 1), "_max")])){
        i.cmp[,"rtmax"] <- cmps[cmps$compound == res$name_old[i], 
                                paste0(substr(s, 1, 1), "_max")]*60
      }
      res[i, paste0("pw_", substr(s, 1, 1))] <- i.cmp[,"rtmax"] -
        i.cmp[,"rtmin"]
      pks <- manualChromPeaks(ydata,
                              chromPeaks = i.cmp,
                              samples = seq_along(fileNames(ydata)),
                              BPPARAM = bpparam(),
                              msLevel = 1L)
      fl <- paste0("output/chr_", s, "/", gsub(
        ":", "_", res$id[i]), ".jpeg")
      if(!(gsub(".*/", "", fl) %in% list.files(paste0(
        "output/chr_", s, "/")))){
        col <- get(paste0("col_", s, "_", pol))
        jpeg(fl)
        chr <- chromatogram(
          ydata, 
          mz = i.cmp[,1:2], rt = i.cmp[,3:4] + 10 * c(-1,1))
        plot(chr, col = col, xaxt = "n")
        axis(1, at = seq(0, 60*30, 3), labels = sprintf(
          "%.2f", seq(0, 30, 3/60))) 
        abline(v=c(rtmin, rtmax), lty = 2, col = "grey")
        abline(v=i.cmp[,3:4])
        dev.off()
      }
      pks <- data.frame(chromPeaks(pks))
      if(s == "tissues"){
        tmp <- unlist(substring(basename(fileNames(ydata)), 25, 40))
        tmp <- gsub("xx00_", "", tmp)
        tmp <- gsub("_N|_P|_NEG|_POS", "", tmp)
        idx <- grepl("_$", tmp)
        tmp[idx] <- unlist(substring(tmp[idx], 1, 15))
      } else if(s == "maturation"){
        tmp <- unlist(substring(basename(fileNames(ydata)), 17, 28))
        tmp <- gsub("xx_00_xQC_", "QC", tmp)
        tmp <- gsub("Rep_", "", tmp)
        tmp <- gsub("Pt_", "Pt", tmp)
      }
      pks$smpl <- tmp[pks$sample]
      data <- get(paste0("data_", s))
      data[pks$smpl, res$id[i]] <- pks$into
      assign(paste0("data_", s), data)
      write.csv(data, paste0("output/data_", s, ".csv"))
    } # close study "s"
    #print(i)
    rm(ad, pol)
  } else{print(paste("Define adduct for compound", res$name_old[i]))}
}

write.csv(res, "output/res_pw.csv")
round(range(res$pw_t, na.rm = T))
round(range(res$pw_m, na.rm = T))
save.image("output/quantification.RData")
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```

