---
title: "Method checks"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

# Read data

```{r}
files = list.files("data/")
files = files[grep("AREA", files)]
data = list()
for(i in 1:length(files)){
  data[[i]] = read.table(paste0("data/", files[i]), 
                  sep = "\t", na.strings = "N/A", skip = 3, row.names = 1, 
                  col.names = colnames(read.table(paste0("data/", files[i]),
                    sep = "\t", header = T)))
  colnames(data[[i]]) = gsub(
    paste0("X", gsub("_all_AREA.txt", "", files[i]), "_"), "", 
    colnames(data[[i]]))
}
data <- do.call("rbind", data)
```

# Which compounds have been detected in a single sample?

```{r}
cmp_n1 = apply(data, 1, function(x) length(which(!is.na(x))))
names(cmp_n1[cmp_n1 == 1])
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```
