---
title: "Remove orbitrap shoulder peaks"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r}
#fluid <- "urine" # specify "urine" or "serum"
polarity <- "POS" # specify "POS" or "NEG"
```

## Libraries

```{r libraries}
#library(chemhelper)
source("../../../R/orbi_filter.R")
```


# Fix files

```{r fix-files}
# Get list of files and make an output folder -------------------------
files  <- list.files(paste0("data/", #fluid, "/", 
  polarity, "_FS_mzXML/"), full.names=T, recursive=T)
dir.create(paste0("data/", #fluid, "/", 
  polarity, "_FS_fixed"), showWarnings = FALSE)
outnames <- sub("\\.mzXML", "\\.mzData", files)
outnames <- sub(paste0(polarity, "_FS_mzXML/"), 
                paste0(polarity, "_FS_fixed/"), outnames)
files    <- files[!file.exists(outnames)]
outnames <- outnames[!file.exists(outnames)]
# make files and outnames into a list ---------------------------------
input <- cbind(files,outnames)
input <- split(input, 1:NROW(input))
# Function to fix a data file -----------------------------------------
xraw_orbifix <- function(file,outname){
  require(xcms)
  #require(chemhelper)
  require(caTools)
  
  xraw <- xcmsRaw(file, profstep = 0)
  #xraw <- readMSData(file, mode = "onDisk")
  
  xraw_out <- xcmsRaw.orbifilter(xraw,
                                 windows_width = 0.3*2,
                                 max_rel_int = 0.2,
                                 keep_isotopes = TRUE,
                                 max_charge = 5,
                                 isotope_mz_tol = 0.005)
  
  write.mzdata(xraw_out, filename = outname)
}
# now make a cluster and convert in parallel --------------------------
lapply(input, function(x){
  xraw_orbifix(x[1], x[2])
  })
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```