---
title: "XCMS processing"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
polarity <- "POS" # specify "POS" or "NEG"
int <- 5e7
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
```


# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
colnames(tmp) <- c("type", "X2", "part", "repl", "polarity", "mode", "X7")
tmp$repl[tmp$part == "entire"] <- tmp$polarity[tmp$part == "entire"]
tmp$polarity[tmp$part == "entire"] <- tmp$mode[tmp$part == "entire"]
tmp$polarity[tmp$type != "matrix"] <- tmp$part[tmp$type != "matrix"]
tmp$mode[tmp$part == "entire"] <- tmp$X7[tmp$part == "entire"]
tmp$mode[tmp$type != "matrix"] <- tmp$repl[tmp$type != "matrix"]
tmp$repl[tmp$type != "matrix"] <- tmp$X2[tmp$type != "matrix"]
tmp$X2[tmp$type != "matrix"] <- tmp$type[tmp$type != "matrix"]
tmp$part[tmp$type != "matrix"] <- tmp$type[tmp$type != "matrix"]
tmp <- tmp[, -c(2, 7)]
injections <- cbind(injections, tmp)
rm(tmp)

injections <- injections[grep("STDmix_04", injections$filename), ]

# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# Peak detection

```{r peak-detection}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, int),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)
```


## Filter low-intensity peaks

```{r filter-intensity}
xdata <- refineChromPeaks(xdata, 
                          param = FilterIntensityParam(
                            nValues = 5, threshold = int)
)
```


## Peak post-processing

```{r peak-postproc}
mnp <- MergeNeighboringPeaksParam(
  expandRt = 2, 
  expandMz = 0.001, 
  ppm = 10,
  minProp = 0.66)
register(SerialParam())
xdata <- refineChromPeaks(xdata, param = mnp)
```


# Aligment

```{r aligment, eval = FALSE}
# Define the hook peaks
pdp <- PeakDensityParam(sampleGroups = xdata$type,
                        minFraction = 0.75,
                        binSize = 0.02,
                        bw = 3)
xdata <- groupChromPeaks(xdata, param = pdp)
# Perform the aligment
pgp <- PeakGroupsParam(span = 0.3,
                       #subset = which(xdata$type == "QC"),
                       #subsetAdjust = "average",
                       minFraction = 1)
xdata <- adjustRtime(xdata, param = pgp)
```


## Checking

The results from the alignment are shown below. 
To visualize the alignment results, the BPC for the whole data set is plotted.

```{r alignment-rtime-plot, fig.width = 12, fig.height = 10, eval = FALSE}
chr_raw <- chromatogram(xdata, aggregationFun = "max", 
                        adjustedRtime = FALSE)
chr_adj <- chromatogram(xdata, aggregationFun = "max")
par(mfrow = c(3, 1), mar = c(0, 4.3, 2, 0.1))
plot(chr_raw, col = paste0(col_type[factor(chr_raw$type)], 40),
     peakType = "none", main = "BPC, raw")
plot(chr_adj, col = paste0(col_type[factor(chr_raw$type)], 40),
     peakType = "none", main = "BPC, adjusted")
plotAdjustedRtime(xdata, col = paste0(col_type[factor(xdata$type)],80))
```


# Correspondance

```{r correspondance}
pdp <- PeakDensityParam(sampleGroups = 1,#xdata$type,
                        #minFraction = 0.66,
                        minSamples = 1,
                        binSize = 0.02,
                        bw = 1)
xdata <- groupChromPeaks(xdata, param = pdp)
```


# Peak filling

```{r peak-filling, eval = FALSE}
fcp <- ChromPeakAreaParam()
xdata <- fillChromPeaks(xdata, param = fcp)
```


# PCA

```{r pca, eval = FALSE}
data <- featureValues(xdata, method = "sum", value = "into")
set.seed(123)
data <- t(imputeRowMinRand(data, method = "from_to",
                           min_fraction = 1/100,
                           min_fraction_from = 1/1000
))
dt <- log10(data)
scaling.pareto <- BioMark::scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plotly::plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = gsub(".mzData", "", rownames(tmp)),
        color = xdata$type)
features <- data.frame(featureDefinitions(xdata))
tmp <- data.frame(pca$rotation)
rownames(tmp) <- paste(sprintf("%.4f",round(features$mzmed, 4)), 
                       sprintf("%.2f",round(features$rtmed/60, 2)), 
                       sep = "_")
plotly::plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp))
```

# Save data

```{r save}
save(xdata, file = paste0("data/RData/data_XCMS_", polarity, ".RData"))
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```