---
title: "Identifications"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

# Main code


```{r}
library(xcms)
library(MsCoreUtils)
library(MetaboCoreUtils)
library(Rdisop)
library(DT)
.ppm <- function(x, ppm = 10) {
  ppm * x / 1e6
}
matchWithPpm <- function(x, y, ppm = 0) {
  lapply(x, function(z, ppm) {
    which(abs(z - y) <= (.ppm(z, ppm)) + 1e-9)
  }, ppm = force(ppm))
}
myimputer <- function(v){
  set.seed(123)
  if (sum(is.na(v)) == 0) {
    return(v)
  } else {
    napos <- which(is.na(v))
    if(min(v, na.rm = TRUE) > 2){
      newval <- runif(length(napos), 1, min(v, na.rm = TRUE)/10)
    } else {
      newval <- runif(length(napos), 0, min(v, na.rm = TRUE)/10)
    }
    out <- v
    out[napos] <- newval
    return(out)
  }
}

cmp <- c()
for(s in c("tissues", "maturation")){
  for(p in c("POS", "NEG")){
    load(paste0(s, "/data/RData/data_", p, ".RData"))
    cmp <- c(cmp, db_exp$compound)
    db_exp$polarity <- p
    db_exp$study <- s
    db_exp$precursor <- as.numeric(db_exp$precursor)
    db_exp$rtime <- as.numeric(db_exp$rtime)
    db_exp$sim <- as.numeric(db_exp$sim)
    if(any(grepl("MS2_sim", colnames(db_exp)))){
      db_exp <- db_exp[,-which(colnames(db_exp) == "MS2_sim")]
    }
    data <- as.data.frame(t(featureValues(xdata, method = "sum", value = "into")))
    assign(paste0("dbexp_", p), db_exp)
    assign(paste0("ms2_", s, "_", p), ms2)
    assign(paste0("xdata_", s, "_", p), xdata)
    assign(paste0("data_", s, "_", p), data)
  }
  dbexp <- rbind(dbexp_NEG, dbexp_POS)
  assign(paste0("dbexp_", s), dbexp)
}
rm(s, p, db_exp, ms2, xdata, dbexp_NEG, dbexp_POS, dbexp, data)
cmp <- unique(cmp)
cmps <- read.csv("compounds.csv")
cmps$id <- cmps$compound
cmps$id <- gsub(")", "", cmps$id)
cmps$id <- gsub("\\(", "_", cmps$id)
cmps$id <- gsub("/", "_", cmps$id)



dbexp <- rbind(dbexp_tissues, dbexp_maturation)
res <- data.frame(matrix(nrow = length(cmp), ncol = 10))
colnames(res) <- c("compound", "RT", "t_ions", "m_ions", "cor_i", "cor_ps",
                   "ip_NEG", "ip_POS", "sim_NEG", "sim_POS")
res$compound <- cmp
for(i in seq(length(cmp))){
  dbi <- dbexp[dbexp$compound == cmp[i],]
  res$RT[i] <- mean(dbi$rtime)
  cori <- c()
  corps <- c()
  for(s in c("tissues", "maturation")){
    if(sum(dbi$study == s) > 0){
      res[i,paste0(substr(s, 1, 1), "_ions")] <- paste(dbi$adduct[dbi$study == s], collapse = "; ")
    } else {
      res[i,paste0(substr(s, 1, 1), "_ions")] <- "-"
    }
    for(p in c("POS", "NEG")){
      if(sum(dbi$study == s & dbi$polarity == p) > 1){
        data <- get(paste0("data_", s, "_", p))
        dt <- data[,dbi$FT[dbi$study == s & dbi$polarity == p]]
        dt <- apply(dt, 2, myimputer)
        idx <- colnames(dt) == dbi$FT[dbi$study == s & dbi$polarity == p][1]
        cori <- c(cori, cor(log10(dt[,idx]), log10(dt[,-idx])))
        xdata <- get(paste0("xdata_", s, "_", p))
        chr <- chromatogram(xdata, 
                            mz = dbi$precursor[idx] + 0.01 * c(-1, 1), 
                            rt = res$RT[i]*60 + 15 * c(-1, 1),
                            aggregationFun = "max")
        for(j in seq(ncol(dt)-1)){
          chrj <- chromatogram(xdata, 
                             mz = dbi$precursor[dbi$FT == colnames(dt)[-idx][j]] + 0.01 * c(-1, 1), 
                             rt = res$RT[i]*60 + 15 * c(-1, 1),
                             aggregationFun = "max")
        chrcorx <- rep(NA, length(chr))
        for(k in seq(length(chr))){
          chrcorx[k] <- correlate(chr[[k]], chrj[[k]])
        }
        corps <- c(corps, chrcorx)
        }
      }
    }
  }
  if(length(cori) == 1){
    res$cor_i[i] <- sprintf("%.3f", cori)
  } else if(length(cori) > 1){
    res$cor_i[i] <- paste(sprintf("%.3f", range(cor_i, na.rm = TRUE)), collapse = "-")
  } else {
    res$cor_i[i] <- "-"
  }
  if(length(corps) > 0){
    if(round(min(corps, na.rm = TRUE), 3) == round(max(corps, na.rm = TRUE))){
      res$cor_ps[i] <- sprintf("%.3f", mean(corps, na.rm = TRUE))
    } else {
      res$cor_ps[i] <- paste(sprintf("%.3f", range(corps, na.rm = TRUE)), collapse = "-")
    }
  } else {
    res$cor_ps[i] <- "-"
  }
  dbi <- dbi[!grepl("13C", dbi$adduct),]
  for(p in c("POS", "NEG")){
    if(sum(dbi$polarity == p) > 1){
      res[i, paste0("sim_", p)] <- paste(range(dbi$sim[dbi$polarity == p]), collapse  = "-")
    }else if(sum(dbi$polarity == p) == 1){
      res[i, paste0("sim_", p)] <- dbi$sim[dbi$polarity == p]
    } else {
      res[i, paste0("sim_", p)] <- "-"
    }
    
    if(sum(dbi$polarity == p) > 0){
      fml <- cmps$formula[cmps$id == cmp[i]]
      ad <- dbi$adduct[dbi$polarity == p][1]
      if(ad == "[M+H]+"){
        fml <- addElements(fml, "H")
      } else if(ad == "[M+NH4]+"){
        fml <- addElements(fml, "NH4")
      } else if(ad == "[M-H]-"){
        fml <- subtractElements(fml, "H")
      }  else if(ad == "[M-H+HCOOH]-"){
        fml <- addElements(fml, "CHO2")
      }else {
        print(paste0("Ull!! Add adduct ", ad, " for compound ", cmp[i]))
      }
      iso_thr <- t(getMolecule(fml, maxisotopes = 3)$isotopes[[1]][,1:3]) 
      colnames(iso_thr) <- c("mz", "i")
      for(s in c("tissues", "maturation")){
        if(any(dbi$study == s)){
          xdata <- get(paste0("xdata_", s, "_", p))
          cp <- chromPeaks(xdata)[unlist(as.data.frame(featureDefinitions(xdata))[
            dbi$FT[dbi$polarity == p & dbi$study == s][1], "peakidx"]),]
          plist <- list()
          for(j in seq(nrow(cp))){
            xdataj <- filterFile(xdata, cp[j,"sample"])
            l <- closest(cp[j, "rtmin"], rtime(xdataj))
            m <- closest(cp[j, "rtmax"], rtime(xdataj))
            lm <- seq(l, m)
            i1 <- rep(NA, length(lm))
            i2 <- rep(NA, length(lm))
            i3 <- rep(NA, length(lm))
            for(n in seq(length(lm))){
              sps <- as.data.frame(xdataj[[lm[n]]])
              iso_exp <- matrix(ncol = 2, nrow = 3)
              colnames(iso_exp) <- c("mz", "i")
              for(q in seq(3)){
                idx <- as.numeric(unlist(matchWithPpm(iso_thr[q,"mz"], sps[,"mz"], ppm = 10)))
                if(length(idx) > 0){
                  iso_exp[q,1] <- sps[idx,1]
                  iso_exp[q,2] <- sps[idx,2]
                }
              }
              i1[n] <- iso_exp[1,2]
              i2[n] <- iso_exp[2,2]
              i3[n] <- iso_exp[3,2]
            } # end lm "n"
            idx <- which(i1 > mean(i1, na.rm = TRUE))
            i1 <- i1[idx]
            i2 <- i2[idx]
            i3 <- i3[idx]
            plist[[j]] <- cbind(i1, i2, i3)
          }
        }
        assign(paste0("plist_", s), plist)
      }
      if(exists("plist_maturation") & exists("plist_tissues")){
        plist <- c(plist_maturation, plist_tissues)
        rm(plist_maturation, plist_tissues)
      } else if(exists("plist_maturation")){
        plist <- plist_maturation
        rm(plist_maturation)
      } else if(exists("plist_tissues")){
        plist <- plist_tissues
        rm(plist_tissues)
      }
      iso_exp <- do.call("rbind", plist)
      iso_exp <- iso_exp[complete.cases(iso_exp),]
      iso_exp_r <- as.data.frame(iso_exp / rowSums(iso_exp))
      iso_exp_r$i1d <- abs(iso_thr[1,2] - iso_exp_r$i1) 
      iso_exp_r$i2d <- abs(iso_thr[2,2] - iso_exp_r$i2) 
      iso_exp_r$i3d <- abs(iso_thr[3,2] - iso_exp_r$i3) 
      res[i, paste0("ip_", p)] <- round(median((1-(abs(iso_thr[1,2] - iso_exp_r$i1) + 
                                                     abs(iso_thr[2,2] - iso_exp_r$i2)  + 
                                                     abs(iso_thr[3,2] - iso_exp_r$i3)))*100))
    } else {
      res[i, paste0("ip_", p)] <- "-"
    }
  }
}
res <- res[order(res$compound),]
res$RT <- sprintf("%.2f", res$RT)
datatable(res, rownames = FALSE, options = list(
  pageLength = nrow(res), dom = "t"))
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```

