---
title: "Identification"
author: "Mar Garcia-Aloy"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
```

# Libraries

```{r, warning=FALSE, message=FALSE}
library(xcms)
library(MetaboCoreUtils)
library(OrgMassSpecR)
library(Rdisop)
library(plotly)

.ppm <- function(x, ppm = 10) {
  ppm * x / 1e6
}
matchWithPpm <- function(x, y, ppm = 0) {
  lapply(x, function(z, ppm) {
    which(abs(z - y) <= (.ppm(z, ppm)) + 1e-9)
  }, ppm = force(ppm))
}
```

# Data import

```{r}
study <- "tissues" # specify "maturation" or "tissues"

load(paste0(study, "/data/RData/data_XCMS_entire_POS.RData"))
feat_pos <- as.data.frame(featureDefinitions(xdata))
rownames(feat_pos) <- gsub("FT", "P", rownames(feat_pos))
data <- featureValues(xdata, method = "sum", value = "into")
rownames(data) <- gsub("FT", substring("P", 1, 1), rownames(data))
colnames(data) <- gsub("_POS_FS.mzData", "", colnames(data))
colnames(data) <- gsub(".*tissues_", "", colnames(data))
data <- data[, order(colnames(data))]
data_pos <- data


load(paste0(study, "/data/RData/data_XCMS_entire_NEG.RData"))
feat <- as.data.frame(featureDefinitions(xdata))
rownames(feat) <- gsub("FT", "N", rownames(feat))
data <- featureValues(xdata, method = "sum", value = "into")
rownames(data) <- gsub("FT", substring("N", 1, 1), rownames(data))
colnames(data) <- gsub("_NEG_FS.mzData", "", colnames(data))
colnames(data) <- gsub(".*tissues_", "", colnames(data))

feat <- rbind(feat, feat_pos)
data <- data[, order(colnames(data))]
all(colnames(data_pos) == colnames(data))
data <- rbind(data, data_pos)
rm(feat_pos, data_pos)

feat <- subset(feat, select = c("mzmed", "rtmed"))
feat$mean <- rowMeans(data)
```

# Ions

```{r}
sn <- data.frame(
  "C" = rep(seq(18, 20), each = 4),
  "db" = rep(seq(0, 3), 3)
)
sn$formula <- paste0("C", sn$C, "H", sn$C*2 - 2*sn$db, "O2")
sn$sn <- paste0(sn$C, ":", sn$db)
sn$mass <- NA
for(i in seq(nrow(sn))){
  sn$mass[i] <- getMolecule(sn$formula[i])$exactmass
}


ids <- readxl::read_xlsx("identification.xlsx")
ions <- data.frame(matrix(ncol = 6, nrow = 0))
colnames(ions) <- c("class", "compound", "RT", "mz", "adduct", "polarity")
for(i in seq(nrow(ids))){
  i.ions <- unlist(strsplit(ids$ions[i], "; "))
  if(grepl("D", ids$formula[i])){
    j.mass <- Rdisop::getMolecule(ids$formula[i])$exactmass
  } else {
    j.mass <- MonoisotopicMass(formula = ListFormula(ids$formula[i]))
  }
  for(j in seq(length(i.ions))){
    j.add <- gsub(".*\\[", "[", i.ions[j])
    j.add <- gsub("-H\\+HCOOH", "\\+CHO2", j.add)
    if(j.add %in% c(adductNames(polarity = "positive"), 
                    adductNames(polarity = "negative"))){
      j.mz <- unlist(mass2mz(j.mass, j.add))
    } else if(grepl("C2H8N", j.add)){
      if(grepl("2M", j.add)){
        j.mz <- j.mass*2 + getMolecule("C2H8N")$exactmass
      } else {
        j.mz <- j.mass + getMolecule("C2H8N")$exactmass
      }
    } else if(grepl("-PA", j.add)){
      j.mz <- j.mass - getMolecule("H2PO4")$exactmass
    } else if(grepl("-PI", j.add)){
      if(grepl("NH4", j.add)){
        j.mz <- as.numeric(mass2mz(j.mass, "[M+NH4]+")) - getMolecule("H2PO4C6H12O6")$exactmass
      } else {
        j.mz <- j.mass - getMolecule("H2PO4C6H12O6")$exactmass
      }
    } else if(grepl("-mPA", j.add)){
      j.mz <- j.mass - getMolecule("H2PO4CH2")$exactmass
    } else if(grepl("-CH3", j.add)){
      j.mz <- j.mass - getMolecule("CH3")$exactmass
    } else if(grepl("-CH2", j.add)){
      if(grepl("2M", j.add)){
        j.mz <- j.mass*2 - getMolecule("CH3")$exactmass
      } else {
        j.mz <- j.mass - getMolecule("CH3")$exactmass
      }
    } else if(grepl(":", j.add)){
      if(grepl("H-", j.add)){
        j.mz <- mass2mz(j.mass,
                        paste0(substr(j.add, 1, 4), 
                               substr(j.add, nchar(j.add)-1, nchar(j.add)))) - 
          sn$mass[sn$sn == substr(j.add, 6, nchar(j.add)-2)]
      } else{
        j.mz <- sn$mass[sn$sn == gsub("\\[", "", gsub("-H]-", "", j.add))]
        j.mz <- as.numeric(
          mass2mz(j.mz, gsub(gsub("\\[", "", gsub("-H]-", "", j.add)), "M", j.add)))
      }
    }
    if(grepl("13C", i.ions[j])){
      if(grepl("\\(", i.ions[j])){
        j.mz <- j.mz + 1.003355*as.numeric(gsub("\\(.*", "", i.ions[j]))
      } else {
        j.mz <- j.mz + 1.003355
      }
    } 
    if(substr(i.ions[j], nchar(i.ions[j]), nchar(i.ions[j])) == "+"){
      i.pol <- "POS"
    } else if(substr(i.ions[j], nchar(i.ions[j]), nchar(i.ions[j])) == "-"){
      i.pol <- "NEG"
    }
    
    ions[nrow(ions)+1, ] <- c(ids$class[i], ids$compound[i], ids$RT[i], j.mz, 
                              i.ions[j], i.pol)
  }
}
ions$RT <- as.numeric(ions$RT)
ions$mz <- as.numeric(ions$mz)
```

# Features

```{r}
feat$class <- NA
feat$compound <- NA
feat$adduct <- NA
feat$ppm <- NA
feat$rtdev <- NA
for(i in seq(nrow(feat))){
  idx <- unlist(matchWithPpm(feat$mzmed[i], ions$mz, ppm = 10))
  idx <- idx[substr(ions$polarity[idx], 1, 1) == 
               substr(rownames(feat)[i], 1, 1)]
  idx <- idx[abs(feat$rtmed[i] - ions$RT[idx]*60) < 10]
  if(length(idx) > 1){
    if(length(unique(gsub(" .*|_.*", "", ions$compound[idx]))) > 1){
      if(length(unlist(matchWithPpm(c(337.27372, 573.48829), 
                                    ions$mz[idx][1], ppm = 10))) == 0)
        print(paste("ULL!! Check ion", round(ions$mz[idx][1], 5), "(can be",
                    paste(ions$compound[idx], collapse = " - "), ")"))
    }
    idx <- idx[which.min(abs(feat$rtmed[i] - ions$RT[idx]*60) )]
  }
  if(length(idx) == 1){
    feat$class[i] <- ions$class[idx]
    feat$compound[i] <- ions$compound[idx]
    feat$adduct[i] <- ions$adduct[idx]
    feat$ppm[i] <- ((feat$mzmed[i] - ions$mz[idx])/ions$mz[idx])*1e6
    feat$rtdev[i] <- feat$rtmed[i]/60 - ions$RT[idx]
  }
}
feat <- feat[order(rownames(feat)),]
feat$class[is.na(feat$class)] <- "X"
```

# PCA

```{r}
#data <- data[rownames(data) %in% feat$FT, ]
#sp_ts <- grep("skin|pulp|seeds", colnames(data))
sp_ts <- seq(ncol(data))
set.seed(123)
dt <- t(imputeRowMinRand(as.matrix(data[, sp_ts]), method = "from_to",
                         min_fraction = 1/100,
                         min_fraction_from = 1/1000))
dt <- log10(dt)
scaling.pareto <- BioMark::scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
class <- colnames(data)
class <- gsub("pt11_", "", class)
class <- gsub("_.*", "", class)
class[grep("QC", colnames(data))] <- "QC"
class[grep("solv", colnames(data))] <- "solv"
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp),
        color = class[sp_ts])

tmp <- data.frame(pca$rotation)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp),
        color = substr(rownames(tmp), 1, 1))

all(colnames(dt) == feat$FT)
col_class_cmps <- c("#E41A1C", "#974661", "#4A72A6", "#3E8E93", "#48A462", "#5D995D", "#90CC90",
                    "#7E6E85", "#A35390", "#D16948", "#FF7F00", "#FFB716", "#FFF02D",
                    "#E1C62F", "#B97B2A", "#B75F49", "#DB728C", "#EC83BA", "#C28EA9", 
                    "#999999", "#FFFFBF50")
names(col_class_cmps) <- c("FFA", "Lyso_PA", "Lyso_PE", "Lyso_PG", "Lyso_PI", "PA", "mPA",
                           "PC", "PE", "PG", "PI", "PS", "CAR", "MAG", "CER", "DAG", 
                           "DGDG", "Lyso_PC", "MGDG", "TAG", "X")
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp),
        color = feat$class,
        colors = col_class_cmps)

slices <- data.frame(table(feat$class))$Freq
lbls <- paste0(data.frame(table(feat$class))$Var1, "\n(n=", 
               data.frame(table(feat$class))$Freq, ", ",
               round((data.frame(table(feat$class))$Freq/nrow(feat))*100), "%)")
pie(slices, lbls)
```

# Table

```{r}
load("../../R/ann_order.RData")
feat$adduct[!is.na(feat$adduct)][!feat$adduct[!is.na(feat$adduct)] %in% ann]
feat$adduct <- factor(feat$adduct, levels = ann)
feat <- feat[order(feat$compound, feat$adduct),]
feat$rtmed <- sprintf("%.2f", as.numeric(feat$rtmed)/60)
feat$mzmed <- sprintf("%.4f", as.numeric(feat$mzmed))
feat$ppm <- sprintf("%.2f", feat$ppm)
feat$rtdev <- sprintf("%.2f", feat$rtdev)

DT::datatable(feat)

target <- readxl::read_xlsx("../target/data/data_tissues.xlsx", sheet = "raw_data")
colnames(target)[1] <- "ID"
feat <- feat[!is.na(feat$compound), ]
cmps <- unique(feat$compound)
mydb <- data.frame(matrix(ncol = 6, nrow = length(cmps)))
colnames(mydb) <- c("class", "compound", "formula", "RT", "ions", "target")
mydb$compound <- cmps
data[is.na(data)] <- 0
for(i in seq(nrow(mydb))){
  idx <- which(feat$compound == cmps[i])
  mydb$class[i] <- unique(feat$class[idx])
  mydb$formula[i] <- ids$formula[ids$compound == feat$compound[idx][1]]
  mydb$RT[i] <- sprintf("%.2f", mean(as.numeric(feat$rtmed[idx])))
  mydb$ions[i] <- paste(feat$adduct[idx], collapse = "; ")
  if(ids$target[ids$compound == cmps[i]] != "X"){
    if(length(idx) == 1){
      i.corr <- sprintf("%.3f", cor(
        data[rownames(feat)[idx],grep("pt11", colnames(data))], 
        t(target[target$ID == ids$target[ids$compound == cmps[i]], 
                 grep("pt11_entire", colnames(target))]))
      )
    } else {
      i.corr <- paste(sprintf("%.3f", range(cor(
        t(data[rownames(feat)[idx],grep("pt11", colnames(data))]), 
        t(target[target$ID == ids$target[ids$compound == cmps[i]], 
                 grep("pt11_entire", colnames(target))])))), collapse = "-")
    }
    mydb$target[i] <- paste0(ids$target[ids$compound == cmps[i]], ": ", i.corr)
  } else {
    mydb$target[i] <- paste(ids$target[ids$compound == cmps[i]])
  }
}
mydb <- mydb[order(mydb$class, mydb$RT, mydb$compound), ]
DT::datatable(mydb, rownames = FALSE)
```

# Rentention times

```{r}
cmp.class <- unique(mydb$class)
for(i in seq(length(cmp.class))){
  i.mydb <- mydb[mydb$class == cmp.class[i], ]
  C <- gsub("H.*", "", i.mydb$formula)
  C <- as.numeric(gsub("C", "", C))
  db <- as.numeric(
    gsub(" .*", "", gsub(".*:", "", 
                         do.call(rbind, strsplit(i.mydb$compound, "_"))[,1])))
  rt <- as.numeric(i.mydb$RT)
  
  idx <- which(i.mydb$compound %in% ids$compound[which(ids$comments == 
                                                         "RT not sure")])
  if(length(idx) == 0){
    idx <- length(rt)+1
  }
  md <- lm(rt[-idx]~C[-idx]+db[-idx])
  plot(rt, C, col = "white", 
       main = paste0(
         cmp.class[i], "\n", "RT=", 
         sprintf("%.3f", md$coefficients["(Intercept)"]),
         "+ C*", sprintf("%.3f", md$coefficients["C[-idx]"]), "+ db*",
         sprintf("%.3f", md$coefficients["db[-idx]"])))
  #if(cmp.class[i] == "TAG"){
  text(rt, C, db)
  #} else if(cmp.class[i] == "DAG"){
  #  text(rt, C, paste(gsub(".*FA", "", i.mydb$compound), "\n", db))
  #}
  #idx <- which(C == 37)
  #if(length(idx) > 0){
  #  text(rt[idx], C[idx], db[idx], col = "forestgreen")
  #}
  idx <- which(abs((md$coefficients["(Intercept)"] + (C*md$coefficients["C[-idx]"]) +
                      (db*md$coefficients["db[-idx]"]) - as.numeric(rt))*60) > 10)
  if(length(idx) > 0){
    text(rt[idx], C[idx], db[idx], col = "red")
  }
  idx <- which(i.mydb$compound %in% ids$compound[which(ids$comments == 
                                                         "RT not sure")])
  if(length(idx) > 0){
    text(rt[idx], C[idx], db[idx], col = "pink")
  }
  abline(h = seq(min(C), max(C), 2), lty = 3, col = "grey")
}
```


```{r, eval = FALSE}
C <- gsub("H.*", "", mydb$formula)
C <- as.numeric(gsub("C", "", C))
db <- as.numeric(
  gsub(" .*", "", gsub(".*:", "", 
                       do.call(rbind, strsplit(mydb$compound, "_"))[,1])))
rt <- as.numeric(mydb$RT)

idx <- which(mydb$compound %in% ids$compound[which(ids$comments == "RT not sure")])
if(length(idx) == 0){
  idx <- length(rt)+1
}
md <- lm(rt[-idx]~C[-idx]+db[-idx])
plot(rt, C, col = "white", 
     main = paste0("RT=", 
                   sprintf("%.3f", md$coefficients["(Intercept)"]),
                   "+ C*", sprintf("%.3f", md$coefficients["C[-idx]"]), "+ db*",
                   sprintf("%.3f", md$coefficients["db[-idx]"])))
text(rt, C, db)
idx <- which(C == 35)
if(length(idx) > 0){
  text(rt[idx], C[idx], db[idx], col = "forestgreen")
}
idx <- which(abs((md$coefficients["(Intercept)"] + (C*md$coefficients["C[-idx]"]) +
                    (db*md$coefficients["db[-idx]"]) - as.numeric(rt))*60) > 10)
text(rt[idx], C[idx], db[idx], col = "red")
abline(h = seq(min(C), max(C), 2), lty = 3, col = "grey")
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```
