---
title: "Real-time sequence evaluation"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
polarity <- "NEG" # specify "POS" or "NEG"
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
```

# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
colnames(tmp) <- c("order", "project", "pt", "time", "type", "rep", "polarity", "mode")
tmp$mode[tmp$polarity == "FS"] <- tmp$polarity[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$rep[tmp$rep == polarity] <- tmp$type[tmp$rep == polarity] 
idx <- tmp$time %in% c("solveq", "blank", "STDmix")
tmp$type[idx] <- tmp$time[idx]
tmp$time[idx] <- 0
idx <- grep("QC", tmp$pt)
tmp$type[idx] <- paste(tmp$pt[idx], tmp$time[idx], sep = "_")
tmp$pt[idx] <- "xx"
tmp$time[idx] <- 0
tmp$type[tmp$type == "Rep" | tmp$type == "MIX"] <- "study"
injections <- cbind(injections, tmp)
rm(tmp)
injections$color <- 1
injections$color[injections$type == "xQC"] <- 2   # red
injections$color[injections$type == "study"] <- 3 # green
injections$color[injections$type == "slv"] <- 4   # blue
injections$color[injections$type == "slveq"] <- 5 # cyan
injections$color[injections$type == "QCeq"] <- 6  # pink
injections$color[grep("QCdl", injections$type)] <- 7 # yellow
injections$color[grep("QCrw", injections$type)] <- 7 # yellow
injections$color[injections$type == "STDmix"] <- 8  # grey

#injections <- injections[grep("slv_01", injections$filename):nrow(injections),]

# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# Get the data of interest

```{r manualchrompeaks}
cmps <- read.csv("data/compounds.csv")
cmps <- cmps[cmps$type == "equiSPLASH" & cmps$formula != "" & cmps[,polarity] != "",]
cmps <- cmps[cmps$RT > 0, ]
cmps$mz <- NA
for(i in 1:nrow(cmps)){
  cmps$mz[i] <- unlist(MetaboCoreUtils::mass2mz(Rdisop::getMolecule(
    cmps$formula[i])$exactmass, cmps[i, polarity]))
}

if(polarity == "NEG"){
  cmps$RT[cmps$abr == "PE_15_0_X_18_1"]    <- 17.36*60
  cmps$RT[cmps$abr == "PG_15_0_X_18_1_d7"] <- 16.52*60
  cmps$RT[cmps$abr == "PI_15_0_X_18_1_d7"] <- 16.31*60
  cmps$RT[cmps$abr == "PS_15_0_X_18_1_d7"] <- 16.36*60
  cmps$RT[cmps$abr == "ceramide_C15_d7"]   <- 17.24*60
  cmps$RT[cmps$abr == "lysoPA_17_0"]       <- 10.20*60
  cmps$RT[cmps$abr == "PA_15_0_X_18_1_d7"] <- 16.92*60
  cmps$RT[cmps$abr == "carnitine_24_0_d4"] <- 15.20*60
}

cmps.mx <- cbind(c(cmps$mz - 0.01), 
                 c(cmps$mz + 0.01), 
                 c(cmps$RT - 10), 
                 c(cmps$RT + 10))
rownames(cmps.mx) <- cmps$abr
colnames(cmps.mx) <- c("mzmin", "mzmax", "rtmin", "rtmax")

peaks <- manualChromPeaks(data_raw,
                          chromPeaks = cmps.mx,
                          samples = seq_along(fileNames(data_raw)),
                          BPPARAM = bpparam(),
                          msLevel = 1L)
data <- data.frame(chromPeaks(peaks))
data$id <- substr(data_raw$filename[data$sample], 17, 28)
data$compound <- NA
for(i in 1:nrow(data)){
  data$compound[i] <- paste(cmps$name[unlist(CompoundDb::matchWithPpm(
    data$mz[i], cmps$mz, ppm = 10))], collapse = "; ")
}
table(data$compound)

palette <- colorRampPalette(colors=c("#F5C710", "#DF536B"))
cols <- palette(length(data_raw$filename))
```

## Plots

```{r manualchrompeaks-plot}
for(i in seq(nrow(cmps))){
  idx <- which(data$compound == cmps$name[i])
  print(cmps$name[i])
  
  chr <- chromatogram(data_raw, 
                      mz = c(cmps.mx[i,1], cmps.mx[i,2]), 
                      rt = c(cmps.mx[i,3]-10, cmps.mx[i,4]+10))
  plot(chr, col = cols)
  abline(v=c(cmps.mx[i, 3:4]), col = "grey", lty = 2)
  
  for(j in 1:10){
    if(data_raw$type[data$sample[idx]][which.max(abs(mean(data$rt[idx]) - 
                                                     data$rt[idx]))] == "slv"){
      idx0 <- idx
      idx <- idx[-which.max(abs(mean(data$rt[idx]) - data$rt[idx]))]
    }
  }
  plot(data$rt[idx]/60, xlab = "", ylab = "", 
       main = paste("RT (delta =", 
                    sprintf("%.2f", round(max(data$rt[idx]/60) - 
                                            min(data$rt[idx]/60), 2)), "min)"), 
       pch = 16, col = data_raw$color[data$sample[idx]],
       ylim = c(min(min(data$rt[idx]/60), mean(data$rt[idx]/60) - 1/60),
                max(max(data$rt[idx]/60), mean(data$rt[idx]/60) + 1/60)))
  abline(h = mean(data$rt[idx]/60), lty = 2)
  abline(h = mean(data$rt[idx]/60) + 1/60 *c(-1, 1), lty = 2, col = "grey")
  if(exists("idx0")){
    idx <- which(data$compound == cmps$name[i])
    rm(idx0)
  }
  
  ppm <- ((data$mz[idx] - cmps$mz[i])/cmps$mz[i])*1e6
  for(j in 1:10){
    if(data_raw$type[data$sample[idx]][which.max(abs(ppm))] == "slv"){
      idx0 <- idx
      idx <- idx[-which.max(abs(ppm))]
      ppm <- ((data$mz[idx] - cmps$mz[i])/cmps$mz[i])*1e6
    }
  }
  plot(ppm, xlab = "", ylab = "", main = "mz deviations (ppm)", pch = 16, 
       col = data_raw$color[data$sample[idx]],
       ylim = c(min(min(ppm), -2), 
                max(max(ppm), 2)))
  abline(h = 0, lty = 2)
  abline(h = c(-2, 2), lty = 2, col = "grey")
  if(exists("idx0")){
    idx <- which(data$compound == cmps$name[i])
    rm(idx0)
  }
  
  plot(data$into[idx], xlab = "", ylab = "", 
       main = paste("Intensity: CV(QC) =", 
                    round(
                      (sd(data$into[idx][grep("xQC", data$id[idx])]) / 
                         mean(data$into[idx][grep("xQC", data$id[idx])]))*100), 
                    "%"),
       pch = 16, col = data_raw$color[data$sample[idx]])
  points(grep("xQC", data$id[idx]), data$into[idx][grep("xQC", data$id[idx])], 
         type = "b", lty = 2, col = "grey")
  abline(h = mean(data$into[idx][grep("xQC", data$id[idx])]) + 
           sd(data$into[idx][grep("xQC", data$id[idx])]) * c(-1, 1), 
         lty = 3, col = "grey")
}
rm(i, j, idx, peaks, chr, ppm)
```


# Aligment

```{r aligment}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, 1e5),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)
pdp <- PeakDensityParam(sampleGroups = xdata$type,
                        minFraction = 0.75,
                        binSize = 0.02,
                        bw = 3)
xdata <- groupChromPeaks(xdata, param = pdp)
pgp <- PeakGroupsParam(span = 0.3,
                       subset = which(xdata$type == "xQC"),
                       subsetAdjust = "average",
                       minFraction = 1)
xdata <- adjustRtime(xdata, param = pgp)
```

## Plots

```{r aligment-plots}
for(i in seq(nrow(cmps.mx))){
  print(cmps$name[i])
  chr_raw <- chromatogram(xdata, 
                          mz = cmps.mx[i, 1:2], 
                          rt = c(cmps.mx[i,3]-10, cmps.mx[i,4]+10),
                          include = "none",
                          adjustedRtime = FALSE)
  chr_adj <- chromatogram(xdata, 
                          mz = cmps.mx[i, 1:2], 
                          rt = c(cmps.mx[i,3]-10, cmps.mx[i,4]+10),
                          include = "none")
  par(mfrow = c(2, 1), mar = c(3,2,1,0.5))
  plot(chr_raw, col = cols)
  plot(chr_adj, col = cols)
}
```



# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```