---
title: "Real-time sequence evaluation"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
k <- 1
polarity <- "POS" # specify "POS" or "NEG"
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
library(plotly)
library(magrittr)
```

# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
colnames(tmp) <- c("order", "project", "pt", "time", "type", "rep", "polarity", "mode")
tmp$mode[tmp$polarity == "FS"] <- tmp$polarity[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$rep[tmp$rep == polarity] <- tmp$type[tmp$rep == polarity] 
idx <- tmp$time %in% c("solveq", "blank", "STDmix")
tmp$type[idx] <- tmp$time[idx]
tmp$time[idx] <- 0
idx <- grep("QC", tmp$pt)
tmp$type[idx] <- paste(tmp$pt[idx], tmp$time[idx], sep = "_")
tmp$pt[idx] <- "xx"
tmp$time[idx] <- 0
tmp$type[tmp$type == "Rep" | tmp$type == "MIX"] <- "study"
injections <- cbind(injections, tmp)
rm(tmp)
injections$color <- 1
injections$color[injections$type == "xQC"] <- 2   # red
injections$color[injections$type == "study"] <- 3 # green
injections$color[injections$type == "slv"] <- 4   # blue
injections$color[injections$type == "slveq"] <- 5 # cyan
injections$color[injections$type == "QCeq"] <- 6  # pink
injections$color[grep("QCdl", injections$type)] <- 7 # yellow
injections$color[grep("QCrw", injections$type)] <- 7 # yellow
injections$color[injections$type == "STDmix"] <- 8  # grey

# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# Get the data of interest

```{r cmps}
cmps <- read.csv("data/compounds.csv")
cmps <- cmps[cmps$type == "equiSPLASH" & cmps$formula != "" & cmps$POS != "",]
cmps <- cmps[cmps$RT > 0, ]
cmps$mz <- NA
for(i in 1:nrow(cmps)){
  cmps$mz[i] <- unlist(MetaboCoreUtils::mass2mz(Rdisop::getMolecule(
    cmps$formula[i])$exactmass, cmps$POS[i]))
}


cmps.mx <- cbind(c(cmps$mz - 0.01), 
                 c(cmps$mz + 0.01), 
                 c(cmps$RT - 10), 
                 c(cmps$RT + 10))
rownames(cmps.mx) <- cmps$abr
colnames(cmps.mx) <- c("mzmin", "mzmax", "rtmin", "rtmax")

#peaks <- manualChromPeaks(data_raw,
#                          chromPeaks = cmps.mx,
#                          samples = seq_along(fileNames(data_raw)),
#                          BPPARAM = bpparam(),
#                          msLevel = 1L)
#data <- data.frame(chromPeaks(peaks))
#data$id <- substr(data_raw$filename[data$sample], 17, 28)
#data$compound <- NA
#for(i in 1:nrow(data)){
#  data$compound[i] <- paste(cmps$name[unlist(CompoundDb::matchWithPpm(
#    data$mz[i], cmps$mz, ppm = 10))], collapse = "; ")
#}
```

# Plots

```{r plots}
print(cmps$name[k])
cmps.mx.k <- matrix(cmps.mx[k, ], nrow = 1)
colnames(cmps.mx.k) <- c("mzmin", "mzmax", "rtmin", "rtmax")
peaks <- manualChromPeaks(data_raw,
                          chromPeaks = cmps.mx.k,
                          samples = seq_along(fileNames(data_raw)),
                          BPPARAM = bpparam(),
                          msLevel = 1L)
data <- data.frame(chromPeaks(peaks))
data$ppm <- ((data$mz - cmps$mz[k])/cmps$mz[k])*1e6

names <- paste0(substr(data_raw$filename[data$sample], 1, 5), 
                substr(data_raw$filename[data$sample], 17, 28))

plot_ly(y = data$rt/60, x = data$sample, 
        color = factor(data_raw$color[data$sample]), 
        text = names) %>% 
  layout(showlegend  = F, title = "RT") %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y = mean(data$rt)/60, yend = mean(data$rt)/60, 
               line = list(color = "black", width = 0.1, dash = "dot")) %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y =( mean(data$rt)/60)-(1/60), 
               yend = (mean(data$rt)/60)-(1/60), 
               line = list(color = "grey", width = 0.1, dash = "dot"))  %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y =( mean(data$rt)/60)+(1/60), 
               yend = (mean(data$rt)/60)+(1/60), 
               line = list(color = "grey", width = 0.1, dash = "dot"))%>% 
  add_markers(y = data$rt/60, x = data$sample)

plot_ly(y = data$ppm, x = data$sample, 
        color = factor(data_raw$color[data$sample]), 
        text = names) %>% 
  layout(showlegend  = F, title = "mz deviations (ppm)") %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y =-2, yend = -2, 
               line = list(color = "grey", width = 0.1, dash = "dot"))  %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y =2, yend = 2, 
               line = list(color = "grey", width = 0.1, dash = "dot"))%>% 
  add_markers(y = data$ppm, x = data$sample)


plot_ly(y = data$into, x = data$sample, 
        color = factor(data_raw$color[data$sample]), 
        text = names) %>% 
  layout(showlegend  = F, 
         title = paste("Intensity: CV(QC) =", 
                       round(
                         (sd(data$into[data_raw$type[data$sample] == "xQC"]) / 
                            mean(data$into[data_raw$type[data$sample] == "xQC"
                            ]))*100), "%")) %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y = mean(data$into[data_raw$type[data$sample] == "xQC"]) - 
                 sd(data$into[data_raw$type[data$sample] == "xQC"]), 
               yend = mean(data$into[data_raw$type[data$sample] == "xQC"]) - 
                 sd(data$into[data_raw$type[data$sample] == "xQC"]), 
               line = list(color = "grey", width = 0.1, dash = "dot"))  %>% 
  add_segments(x = 0, xend = nrow(injections), 
               y = mean(data$into[data_raw$type[data$sample] == "xQC"]) + 
                 sd(data$into[data_raw$type[data$sample] == "xQC"]), 
               yend = mean(data$into[data_raw$type[data$sample] == "xQC"]) + 
                 sd(data$into[data_raw$type[data$sample] == "xQC"]), 
               line = list(color = "grey", width = 0.1, dash = "dot"))%>% 
  add_markers(y = data$into, x = data$sample)
```



# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```