---
title: "STDs: Isotopic pattern"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

# Libraries

```{r, message=FALSE, warning=FALSE}
library(xcms)
library(Rdisop)
library(MetaboAnnotation)
library(MetaboCoreUtils)
library(MsCoreUtils)
.ppm <- function(x, ppm = 10) {
  ppm * x / 1e6
}
matchWithPpm <- function(x, y, ppm = 0) {
  lapply(x, function(z, ppm) {
    which(abs(z - y) <= (.ppm(z, ppm)) + 1e-9)
  }, ppm = force(ppm))
}
getmzneut <- function(
  mz = numeric(0),
  adduct = c("[M+H]+", "[M+NH4]+", "[M+Na]+", "[M+K]+", 
             "[M-H]-", "[M+CHO2]-", "[M+Cl]-", "[M-H+HCOONa]-",
             "[2M-H]-", "[2M+H]+",
             "[M+H-H2O]+")){
  addtb <- rbind(
    c("[M+H]+", 1.007276),
    c("[M+NH4]+", 18.034374142),
    c("[M+Na]+", 22.98980),
    c("[M+K]+", 38.96371),
    c("[M-H]-", -1.007276),
    c("[M+CHO2]-", 44.99820),
    c("[M+Cl]-", 34.96885),
    c("[M-H+HCOONa]-", 66.98017),
    c("[2M+H]+", 1.007276),
    c("[2M-H]-", -1.007276),
    c("[M+H-H2O]+", -17.00328)
  )
  if(grepl("2M", adduct)){
    (mz - as.numeric(addtb[addtb[,1] == adduct,2]))/2
  } else {
    mz - as.numeric(addtb[addtb[,1] == adduct,2])
  }
}
getform <- function(mzval = numeric(0),
                    elements = "CHNOPS",
                    ppm = 10){
  Rdisop::decomposeMass(mzval, 
                        ppm = ppm,
                        elements = initializeElements(
                          unlist(strsplit(elements, 
                                          "(?<=.)(?=[[:upper:]])", 
                                          perl=TRUE)))
  )$formula
}
foo <- function (...) 
{
  dargs <- list(...)
  if (!all(vapply(dargs, is.vector, TRUE))) 
    stop("all inputs must be vectors")
  if (!all(vapply(dargs, function(x) !is.null(names(x)), TRUE))) 
    stop("all input vectors must be named.")
  all.names <- unique(names(unlist(dargs)))
  out <- do.call(rbind, lapply(dargs, `[`, all.names))
  colnames(out) <- all.names
  out
}
```

# Main code

```{r}
for(pol in c("POS"#, "NEG"
)){
  fls <- list.files(paste0("tissues/data/", pol, "_FS_fixed/"))
  fls <- fls[grep("STDmix", fls)]
  xdata <- readMSData(
    paste0("tissues/data/", pol, "_FS_fixed/", fls),
    mode = "onDisk")
  cwp <- CentWaveParam(ppm = 20,
                       peakwidth = c(2, 20),
                       prefilter = c(5, 1000000),
                       snthresh = 5,
                       noise = 1000,
                       mzdiff = 0.001,
                       integrate = 2)
  xdata <- findChromPeaks(xdata, param = cwp)
  xdata <- refineChromPeaks(xdata, 
                            param = FilterIntensityParam(
                              nValues = 5, threshold = 1000000)
  )
  cp <- as.data.frame(chromPeaks(xdata))
  cmps <- read.csv("compounds.csv")
  cmps$compound <- gsub(")", "", cmps$compound)
  cmps$compound <- gsub("\\(", "_", cmps$compound)
  cmps$compound <- gsub("/", "_", cmps$compound)
  cmps <- cmps[!cmps$compound %in% c("PC_18:1_18:3",
                                     "PE_18:1_18:3",
                                     "PA_18:1_18:3",
                                     "PG_18:1_18:3",
                                     "PS_18:1_18:3"), ]
  cmps <- cmps[cmps$standard == TRUE & cmps$IS == FALSE, ]
  cmps$exactmass <- NA
  for(i in seq(nrow(cmps))){
    cmps$exactmass[i] <- getMolecule(cmps$formula[i])$exactmass
  }
  cmps$rt <- cmps$rtime*60
  if(pol == "POS"){
    parm <- Mass2MzRtParam(adducts = c("[M+H]+", "[M+NH4]+"), 
                           ppm = 10, toleranceRt = 10)
  }else if(pol == "NEG"){
    parm <- Mass2MzRtParam(adducts = c("[M-H]-", "[M+CHO2]-"), 
                           ppm = 10, toleranceRt = 10)
  }
  
  ft_match <- matchMz(as.data.frame(cp), cmps, parm, 
                      mzColname = "mz", rtColname = "rt")
  ft_match_out <- as.data.frame(matchedData(ft_match))
  tmp <- ft_match_out[!is.na(ft_match_out$target_compound), ]
  tmp2 <- gsub("\\..*", "",rownames(tmp)) #paste(round(tmp$mz), round(tmp$rt))
  any(duplicated(tmp2))
  if(any(duplicated(tmp2))){
    noise <- c()
    dpl <- unique(tmp2[duplicated(tmp2)])
    for(i in unique(dpl)){
      #    i.tmp <- tmp[tmp2 == i, ]
      i.tmp <- tmp[grep(i, gsub("\\..*", "",rownames(tmp))),]
      idx <- which(gsub("\\..*", "",rownames(tmp)) == i)
      #if(length(unique(i.tmp$target_class)) == 1){
      #  ft_match_out$target_compound[idx] <- paste0(
      #    i.tmp$target_class[1], i.tmp$target_C[1], ":", i.tmp$target_db[1])
      #} else {
      ft_match_out$target_compound[idx] <- paste(i.tmp$target_compound, 
                                                 collapse = " - ")
      #}
    }
  }
  #ft_match_out <- ft_match_out[-grep("\\.", rownames(ft_match_out)),]
  cp$compound <- ft_match_out$target_compound
  cp$adduct <- ft_match_out$adduct
  cp <- cp[!is.na(cp$compound),]
  
  
  
  cmpsx <- unique(cp$compound)
  dt_cmps <- data.frame(matrix(ncol = 11, nrow = length(cmpsx)))
  colnames(dt_cmps) <- c("cmp", "formula", "adduct", "i1", "i2", "i3", 
                         "others", "not_formula", "not_i1", "not_i2", "not_i3")
  dt_cmps$cmp <- cmpsx
  
  for(i in seq(20#length(cmpsx)
  )){
    #fml <- unique(cmps$formula[cmps$compound %in% unlist(strsplit(cmpsx[i], " - "))])
    fml <- cmps$formula[cmps$compound == cmpsx[i]]
    dt_cmps$formula[i] <- fml
    cpx <- cp[cp$compound == cmpsx[i],]
    ad <- c(NA, NA)
    for(j in seq(2)){
      ad[j] <- cpx$adduct[cpx$sample == j][which.max(cpx$maxo[cpx$sample == j])]
    }
    ad <- unique(ad)
    if(length(ad) == 1){
      if(ad == "[M+H]+"){
        fml <- addElements(fml, "H")
        dt_cmps$adduct[i] <- ad
      } else if(ad == "[M+NH4]+"){
        fml <- addElements(fml, "NH4")
        dt_cmps$adduct[i] <- ad
      } else if(ad == "[M-H]-"){
        fml <- subtractElements(fml, "H")
        dt_cmps$adduct[i] <- ad
      }  else if(ad == "[M+CHO2]-"){
        fml <- addElements(fml, "CHO2")
        dt_cmps$adduct[i] <- ad
      }else {
        print(paste0("Ull!! Add adduct ", ad, " for compound ", cmpsx[i]))
      }
      iso_thr <- t(getMolecule(fml, maxisotopes = 3)$isotopes[[1]][,1:3]) 
      colnames(iso_thr) <- c("mz", "i")
      #iso_thr[,"i"] <- iso_thr[,"i"]/iso_thr[1,2]
    } else{print(paste0("Ull!! Check compound ", cmpsx[i]))}
    mlist <- list()
    plist <- list()
    for(j in seq(2)){
      xdataj <- filterFile(xdata, j)
      cpxj <- cpx[cpx$sample == j,]
      k <- which.max(cpxj$maxo)
      #pw <- cpxj[k,"rtmax"] - cpxj[k,"rtmin"]
      #pmin <- cpxj[k,"rt"] - pw/4
      #pmax <- cpxj[k,"rt"] + pw/4
      #if(pmin < cpxj[k,"rtmin"]){
      pmin <- cpxj[k,"rtmin"]
      #}
      #if(pmax > cpxj[k,"rtmax"]){
      pmax <- cpxj[k,"rtmax"]
      #}
      l <- closest(pmin, rtime(xdataj))
      m <- closest(pmax, rtime(xdataj))
      lm <- seq(l, m)
      m1 <- rep(NA, length(lm))
      m2 <- rep(NA, length(lm))
      m3 <- rep(NA, length(lm))
      i1 <- rep(NA, length(lm))
      i2 <- rep(NA, length(lm))
      i3 <- rep(NA, length(lm))
      for(n in seq(length(lm))){
        sps <- as.data.frame(xdataj[[lm[n]]])
        iso_exp <- matrix(ncol = 2, nrow = 3)
        colnames(iso_exp) <- c("mz", "i")
        for(p in seq(3)){
          idx <- as.numeric(unlist(matchWithPpm(iso_thr[p,"mz"], sps[,"mz"], ppm = 10)))
          if(length(idx) > 0){
            iso_exp[p,1] <- sps[idx,1]
            iso_exp[p,2] <- sps[idx,2]
          }
        }
        #iso_exp[,"i"] <- iso_exp[,"i"]/iso_exp[1,2]
        m1[n] <- iso_exp[1,1]
        m2[n] <- iso_exp[2,1]
        m3[n] <- iso_exp[3,1]
        i1[n] <- iso_exp[1,2]
        i2[n] <- iso_exp[2,2]
        i3[n] <- iso_exp[3,2]
      }
      idx <- which(i1 > mean(i1, na.rm = TRUE))
      i1 <- i1[idx]
      i2 <- i2[idx]
      i3 <- i3[idx]
      m1 <- m1[idx]
      m2 <- m2[idx]
      m3 <- m3[idx]
      plist[[j]] <- cbind(i1, i2, i3)
      mlist[[j]] <- cbind(m1, m2, m3)
    }
    iso_exp <- do.call("rbind", plist)
    iso_exp <- iso_exp[complete.cases(iso_exp),]
    m_exp <- do.call("rbind", mlist)
    m_exp <- m_exp[complete.cases(m_exp),]
    
    iso_exp_r <- as.data.frame(iso_exp / rowSums(iso_exp))#as.data.frame(t(apply(iso_exp, 1, function(x) x/max(x))))
    iso_exp_r$i1d <- abs(iso_thr[1,2] - iso_exp_r$i1) / iso_thr[1,2]
    iso_exp_r$i2d <- abs(iso_thr[2,2] - iso_exp_r$i2) / iso_thr[2,2]
    iso_exp_r$i3d <- abs(iso_thr[3,2] - iso_exp_r$i3) / iso_thr[3,2]
    
    #dt_cmps$i2pf[i] <- (iso_thr[2,"i"] - median(iso_exp_r[,"i2"])) / 
    #  (quantile(iso_exp_r[,"i2"], 0.95) - quantile(iso_exp_r[,"i2"], 0.05))
    #dt_cmps$i3pf[i] <- (iso_thr[3,"i"] - median(iso_exp_r[,"i3"])) / 
    #  (quantile(iso_exp_r[,"i3"], 0.95) - quantile(iso_exp_r[,"i3"], 0.05))
    
    dt_cmps[i, 4:6] <- apply(iso_exp_r[, 4:6], 2, median)
    mzneutral <- getmzneut(mean(m1), ad)
    myform <- data.frame(formula = getform(mzval = mzneutral, ppm = 10, elements = "CHNOP"))
    myform <- cbind(myform, as.data.frame(do.call(foo, lapply(myform$formula, countElements))))
    myform[is.na(myform)] <- 0
    myform <- myform[myform$C >= 2 & myform$C <= 100,]
    myform <- myform[myform$H >= 2 & myform$H <= 200,]
    myform <- myform[myform$O >= 1 & myform$O <= 20,]
    myform <- myform[myform$N <= 2,]
    myform <- myform[myform$P <= 1,]
    myform$DBE <- myform$C - 1/2*(myform$H) + 1/2*(myform$N + myform$P) + 1
    myform <- myform[myform$DBE%%1 == 0 & myform$DBE > 0,]
    myform <- myform$formula[!myform$formula %in% cmps$formula[cmps$compound == cmpsx[i]]]
    
    dt_cmps$others[i] <- length(myform)
    
    if(length(myform) > 0){
      dev <- matrix(ncol = 3, nrow = length(myform))
      for(j in seq(length(myform))){
        iso_thrx <- t(getMolecule(myform[j], maxisotopes = 3)$isotopes[[1]][,1:3]) 
        colnames(iso_thrx) <- c("mz", "i")
        dev[j, 1] <- median(abs(iso_thrx[1,2] - iso_exp_r$i1) / iso_thrx[1,2])
        dev[j, 2] <- median(abs(iso_thrx[2,2] - iso_exp_r$i2) / iso_thrx[2,2])
        dev[j, 3] <- median(abs(iso_thrx[3,2] - iso_exp_r$i3) / iso_thrx[3,2])
      }
      idx <- which.min(rowSums(dev))
      dt_cmps$not_formula[i] <- myform[idx]
      dt_cmps$not_i1[i] <- dev[idx,1]
      dt_cmps$not_i2[i] <- dev[idx,2]
      dt_cmps$not_i3[i] <- dev[idx,3]
    } else {
      dt_cmps$not_formula[i] <- "X"
      dt_cmps$not_i1[i] <- 9999
      dt_cmps$not_i2[i] <- 9999
      dt_cmps$not_i3[i] <- 9999
    }
  }
  
  #print(DT::datatable(dt_cmps, rownames = FALSE, options = list(
  #  pageLength = nrow(dt_cmps), dom = "t")))
  dt_cmps$i1 <- round(dt_cmps$i1, 3)
  dt_cmps$i2 <- round(dt_cmps$i2, 3)
  dt_cmps$i3 <- round(dt_cmps$i3, 3)
  dt_cmps$not_i1 <- round(dt_cmps$not_i1, 3)
  dt_cmps$not_i2 <- round(dt_cmps$not_i2, 3)
  dt_cmps$not_i3 <- round(dt_cmps$not_i3, 3)
  #dt_cmps <- dt_cmps[order(dt_cmps$cmp),]
  print(dt_cmps[seq(i),])
  print(dt_cmps[dt_cmps$i1[seq(i)] > dt_cmps$not_i1[seq(i)],])
  print(dt_cmps[dt_cmps$i2[seq(i)] > dt_cmps$not_i2[seq(i)],])
  print(dt_cmps[dt_cmps$i3[seq(i)] > dt_cmps$not_i3[seq(i)],])
}
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```

