---
title: "Lipidomics - Untargeted: Standard Mix"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
```


In this document I'm going to plot the extract ion chromatograms (EICs), full scan (FS) and MS2 spectra of compounds included in `STDmix` samples. 

# Libraries

```{r libraries, message=FALSE, warning=FALSE}
library(readxl)
library(xcms)
library(Spectra)
library(Rdisop)
library(CompoundDb)
library(MsCoreUtils)
```

# Data import

## Theoretical

```{r cmps}
cmps <- read_xlsx("//femsrv220.intra.ismaa.it/WATERS/experiments/AB6500_domenico2019/Lipidomics/20210211_Composti_STD_MIX_nativi.xlsx", sheet = "massa esatta")
cmps$Formula[cmps$ID == "PE(18:1/18:1)"] <- "C41H78NO8P"
cmps$Formula[cmps$ID == "PG(18:1/18:2)"] <- "C42H77O10P"
for(i in seq(nrow(cmps))){
  if(is.na(cmps$classe[i])){
    cmps$classe[i] <- cmps$classe[i-1]
  }
}
TAG <- data.frame(cbind(
  rep("TAG", 3),
  c("TAG30:0_FA10:0", "TAG36:0_FA12:0", "TAG24:0_FA08:0"),
  c("C33H62O6", "C39H74O6", "C27H50O6")
))
colnames(TAG) <- colnames(cmps)
cmps <- rbind(cmps, TAG)
cmps$mass <- NA
for(i in seq(nrow(cmps))){
  cmps$mass[i] <- getMolecule(cmps$Formula[i])$exactmass
}


cmpsx <- read_xlsx("C:/Users/garciaalom/Google Drive/laboratory/db_compounds.xlsx")
cmpsx <- cmpsx[which(cmpsx$ID_cmp == "C0612"):which(cmpsx$ID_cmp == "C0713"),]
cmpsx <- subset(cmpsx, select = c("ID_cmp", "compound", "formula", "lipidgrape_min", "lipidgrape_max"))
cmpsx$RT <- rowMeans(cmpsx[,c("lipidgrape_min", "lipidgrape_max")])
cmpsx <- cmpsx[order(cmpsx$RT), ]
cmpsx$ID <- cmpsx$compound
cmpsx <- subset(cmpsx, select = c("ID", "RT"))

cmps$ID <- gsub("-H2O", "", cmps$ID)
cmps$ID <- gsub("-CH3", "", cmps$ID)
cmps <- merge(cmps, cmpsx)

ions <- read_xlsx("C:/Users/garciaalom/Google Drive/projectes/lipidomics_shared/new_rt.xlsx", sheet = "FORMULE") 
ions <- subset(ions, select = c("ID", "POS", "NEG"))
ions <- ions[ions$ID %in% cmps$ID, ]
cmps <- merge(cmps, ions, by = "ID", all = TRUE)
cmps$POS[cmps$POS == "NA"] <- NA
cmps$NEG[cmps$NEG == "NA"] <- NA

target <- rbind(
  read_xlsx("C:/Users/garciaalom/Google Drive/projectes/lipidomics_shared/new_rt.xlsx", sheet = "POS"), 
  read_xlsx("C:/Users/garciaalom/Google Drive/projectes/lipidomics_shared/new_rt.xlsx", sheet = "NEG"))
target$NAME <- gsub("_Na", "", target$NAME)
rm(ions, cmpsx, i)
```

## Experimental

```{r data-import}
for(p in c("POS", "NEG")){
  pth <- paste0("tissues/data/", p, "_FS_fixed/") 
  fls <- list.files(pth) 
  fls <- fls[grep("STDmix", fls)]
  xdata <- readMSData(paste0(pth , fls), mode = "onDisk")
  assign(paste0("xdata_", p), xdata)
  
  pth <- paste0("tissues/data/", p, "_DDA_mzML/") 
  fls <- list.files(pth) 
  fls <- fls[grep("STDmix", fls)]
  ms2spec <- Spectra(paste0(pth, fls), backend = MsBackendDataFrame())
  ms2spec <- ms2spec[msLevel(ms2spec) > 1]
  assign(paste0("ms2_", p), ms2spec)
}
rm(p, pth, fls, xdata, ms2spec)
```

# Output

```{r output, fig.width=10}
for(i in 80#seq(nrow(cmps)) until 80
){
  print(cmps$ID[i])
  print(cmps$Formula[i])
  i.mass <- cmps$mass[i]
  print(unlist(mass2mz(i.mass, adduct = c("[M+H]+", "[M+NH4]+", "[M+Na]+", 
                                          "[M-H]-", "[M-H+HCOOH]-", "[M+Cl]-"))))
  i.rt <- cmps$RT[i]
  if(is.na(i.rt)){
    i.rt <- target$RT[target$NAME == cmps$ID[i]] + 0.3
  }
  if(length(i.rt) == 0){i.rt <- 15}
  for(p in c("POS", "NEG")){
    xdata <- get(paste0("xdata_", p))
    xdata2 <- filterFile(xdata, 2)
    ms2 <- get(paste0("ms2_", p))
    if(p == "POS"){
      i.add <- c("[M+H]+", "[M+NH4]+", "[M+Na]+")
    } else if(p == "NEG"){
      i.add <- c("[M-H]-", "[M-H+HCOOH]-", "[M+Cl]-")
    }
    if(!is.na(cmps[i, p])){
      chr <- chromatogram(
        xdata, 
        mz = unlist(mass2mz(i.mass, cmps[i, p])) + 0.01 * c(-1, 1)
      )
      i.int <- max(intensity(chr[[1]])[closest(i.rt*60-10, rtime(chr[[1]])):
                                         closest(i.rt*60+10, rtime(chr[[1]]))], 
                   na.rm = TRUE)
      i.rt2 <- rtime(chr[[1]])[names(which.max(intensity(chr[[1]])[
        closest(i.rt*60-10, rtime(chr[[1]])):
          closest(i.rt*60+10, rtime(chr[[1]]))]))]
      
      par(mfrow = c(1, 2), mar = c(4, 2, 3, 0.5))
      plot(chr, xaxt="n")
      axis(1, at = seq(0, 60*30, 60), labels = seq(0, 30))
      points(i.rt2, i.int, pch = 8, col = 2)
      
      plot(chr, xaxt="n", xlim = i.rt*60 + 20 * c(-1, 1))
      axis(1, at = seq(0, 60*30, 3), labels = sprintf("%.2f", seq(0, 30, 3/60))) 
      points(i.rt2, i.int, pch = 8, col = 2)
      
      sps <- as.data.frame(xdata2[[closest(i.rt2, rtime(xdata2))]])
    } else {
      i.mz <- unlist(mass2mz(cmps$mass[i], adduct = i.add))
      par(mfrow = c(1, 3), mar = c(4, 2, 3, 0.5))
      for(j in seq(length(i.mz))){
        chr <- chromatogram(xdata, mz = i.mz[j] + 0.10 * c(-1, 1))
        i.int <- max(intensity(chr[[2]])[closest(i.rt*60-10, rtime(chr[[2]])):
                                           closest(i.rt*60+10, rtime(chr[[2]]))], 
                     na.rm = TRUE)
        plot(chr, xaxt="n")
        axis(1, at = seq(0, 60*30, 60), labels = seq(0, 30))
        points(i.rt*60, i.int, pch = 8, col = 2)
      }
      sps <- as.data.frame(xdata2[[closest(i.rt*60, rtime(xdata2))]])
    } # close if is.na cmps$NEG/POS[i]
    sps$irel <- sps$i / max(sps$i)
    
    par(mfrow = c(1, 2), mar = c(4, 2, 3, 0.5))
    plot(sps$mz, sps$irel, type = "h", xlab = "mz", ylab = "relative intensity",
         main = paste0(
           "FS at ", 
           sprintf("%.2f", rtime(xdata2[[closest(i.rt*60, rtime(xdata2))]])/60),
           "min"))
    tmp <- c()
    for(k in seq(0, 3)){
      i.ion <- matchWithPpm(unlist(mass2mz(i.mass, i.add))+1.003355*k, 
                            sps$mz, ppm = 10)
      tmp <- c(tmp, unlist(i.ion))
      for(j in seq(length(i.ion))){
        if(length(i.ion[[j]]) > 0){
          if(sps$irel[i.ion[[j]]] > 0.1){
            text(sps$mz[i.ion[[j]]], sps$irel[i.ion[[j]]],  
                 round(sps$mz[i.ion[[j]]], 4), col = j+1) 
          }
          points(sps$mz[i.ion[[j]]], sps$irel[i.ion[[j]]], col = j+1, type = "h")
        }
      } 
    }
    idx <- which(sps$irel > 0.1)
    idx <- idx[!idx %in% tmp]
    if(length(idx) > 5){
      idx <- order(sps$irel, decreasing = T)
      idx <- idx[!idx %in% tmp]
      idx <- idx[1:5]
    }
    if(length(idx) > 0){
      text(sps$mz[idx], sps$irel[idx], round(sps$mz[idx], 4))
    }
    
    if(!is.na(cmps[i, p])){
      ms2sub <- filterPrecursorMz(ms2, unlist(mass2mz(i.mass, cmps[i, p])) + 0.1 * c(-1, 1))
      ms2sub <- filterRt(ms2sub, i.rt2 + 10 * c(-1, 1))
    } else {
      ms2sub <- c()
    }
    
    if(length(ms2sub) > 0){
      intensitats <- c()
      for(j in seq(length(ms2sub))){
        idx <- c(which(unlist(mz(ms2sub[j])) > 283.2 & 
                         unlist(mz(ms2sub[j])) < 283.9),
                 which(unlist(mz(ms2sub[j])) > 340.7 & 
                         unlist(mz(ms2sub[j])) < 341.8))
        if(length(idx) == 0){
          int.noise <- 1
          int.good <- max(unlist(intensity(ms2sub[j])))
        } else {
          int.noise <- max(unlist(intensity(ms2sub[j]))[idx])
          int.good <- max(unlist(intensity(ms2sub[j]))[-idx])
        }
        intensitats <- c(intensitats, int.good / int.noise)
      }
      j <- order(intensitats, decreasing = T)[1]
      plot(unlist(mz(ms2sub[j])), 
           unlist(intensity(ms2sub[j])) / max(unlist(intensity(ms2sub[j]))), 
           type = "h", 
           ylab = "rel. intensity", #xlab = "mz", 
           xlab = gsub("_DDA.mzML", "", basename(ms2sub[j]@backend@spectraData$dataOrigin)),
           main = paste("MS2", sprintf("%.4f", ms2sub[j]@backend@spectraData$precursorMz), 
                        "@", 
                        sprintf("%.2f", ms2sub[j]@backend@spectraData$rtime/60)),
      )
      idx <- which(unlist(intensity(ms2sub[j])) / max(unlist(intensity(ms2sub[j]))) > 0.1)
      text(unlist(mz(ms2sub[j]))[idx], 
           (unlist(intensity(ms2sub[j])) / max(unlist(intensity(ms2sub[j]))))[idx],
           round(unlist(mz(ms2sub[j]))[idx], 4))  
    } else {
      plot(0, 0, col = "white", xlab= "", ylab = "", xaxt="n", yaxt="n")
      text(0, 0, "Not MS2 avialable")
    }
    
  } # end polarity "p"
} # close compound "i"
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```