---
title: "XCMS processing"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
polarity <- "POS" # specify "POS" or "NEG"
int <- 3e6
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
library(plotly)
```

## Coloring factors

```{r colors}
col_type <- RColorBrewer::brewer.pal(5, name = "Set1")
names(col_type) <- c("xQC",      # red
                     "slv",      # blue
                     "study",    # green
                     "QCrw_05uL",# viola
                     "QCdl_05uL"#,# orange
                     #"slveq",   # yellow
                     #"QCeq",    # brown
                     #"STDmix"   # pink
)
col_type <- c(col_type[1:3],
              rep(col_type[4], 3),
              rep(col_type[5], 3))
names(col_type) <- c("xQC", "slv", "study", 
                     "QCrw_02uL", "QCrw_05uL", "QCrw_10uL", 
                     "QCdl_02uL", "QCdl_05uL", "QCdl_10uL")
plot(1, 1, xaxt = 'n', yaxt = 'n', bty = 'n', 
     xlab = '', ylab = '', xlim = 0:1, ylim = 0:1)
legend("topleft", legend = names(col_type), bty = 'n', 
       col = col_type, pch = 16, pt.cex = 2, cex = 2, ncol = 2)
```


# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_FS_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
colnames(tmp) <- c("order", "project", "pt", "time", "type", "rep", "polarity", "mode")
tmp$mode[tmp$polarity == "FS"] <- tmp$polarity[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$polarity[tmp$polarity == "FS"] <- tmp$rep[tmp$polarity == "FS"] 
tmp$rep[tmp$rep == polarity] <- tmp$type[tmp$rep == polarity] 
idx <- tmp$time %in% c("solveq", "blank", "STDmix")
tmp$type[idx] <- tmp$time[idx]
tmp$time[idx] <- 0
idx <- grep("QC", tmp$pt)
tmp$type[idx] <- paste(tmp$pt[idx], tmp$time[idx], sep = "_")
tmp$pt[idx] <- "xx"
tmp$time[idx] <- 0
tmp$type[tmp$type == "Rep" | tmp$type == "MIX"] <- "study"
injections <- cbind(injections, tmp)
rm(tmp)

injections <- injections[grep("slv_01", injections$filename):nrow(injections),]
#injections <- injections[!injections$type %in% "slv", ] #1.5e7
```


```{r, eval = FALSE}
injections <- injections[!injections$filename %in% 
                           c("x085_lipidgrape_Pt_07_Rep_03_POS_FS.mzData", #4e7
                             #5e7
                             "x032_lipidgrape_Pt_04_Rep_04_POS_FS.mzData",
                             "x036_lipidgrape_Pt_12_Rep_03_POS_FS.mzData",
                             "x043_lipidgrape_Pt_05_Rep_05_POS_FS.mzData",
                             "x044_lipidgrape_Pt_06_Rep_03_POS_FS.mzData",
                             "x057_lipidgrape_Pt_04_Rep_01_POS_FS.mzData",
                             "x061_lipidgrape_Pt_05_Rep_01_POS_FS.mzData",
                             "x067_lipidgrape_Pt_07_Rep_01_POS_FS.mzData",
                             "x075_lipidgrape_Pt_13_MIX_01_POS_FS.mzData",
                             "x056_lipidgrape_QCdl_02uL_03_POS_FS.mzData",
                             #6e7
                             "x022_lipidgrape_Pt_12_MIX_01_POS_FS.mzData",
                             "x029_lipidgrape_Pt_04_Rep_03_POS_FS.mzData",
                             "x047_lipidgrape_QCdl_02uL_01_POS_FS.mzData",
                             "x055_lipidgrape_Pt_09_Rep_02_POS_FS.mzData",
                             "x069_lipidgrape_Pt_02_Rep_01_POS_FS.mzData",
                             "x073_lipidgrape_Pt_08_Rep_03_POS_FS.mzData",
                             "x108_lipidgrape_Pt_11_Rep_02_POS_FS.mzData",
                             #8e7
                              "x016_lipidgrape_Pt_06_Rep_04_POS_FS.mzData", 
                             "x019_lipidgrape_Pt_09_Rep_03_POS_FS.mzData", 
                             "x035_lipidgrape_Pt_08_Rep_05_POS_FS.mzData", 
                             "x068_lipidgrape_Pt_04_Rep_05_POS_FS.mzData",
                             "x070_lipidgrape_QCdl_05uL_01_POS_FS.mzData",
                             "x080_lipidgrape_Pt_01_Rep_03_POS_FS.mzData",
                             "x081_lipidgrape_Pt_01_Rep_02_POS_FS.mzData",
                             "x100_lipidgrape_Pt_03_Rep_03_POS_FS.mzData",
                             "x102_lipidgrape_Pt_09_Rep_01_POS_FS.mzData"
                             ), ]
#injections <- injections[injections$filename %in% 
#                           c("x094_lipidgrape_Pt_02_Rep_02_POS_FS.mzData",
#                             "x114_lipidgrape_Pt_12_Rep_02_POS_FS.mzData"),]
#injections <- injections[injections$filename == "x099_lipidgrape_QCrw_10uL_02_POS_FS.mzData", ]
```


```{r}
# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_FS_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# Peak detection

```{r peak-detection}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, int),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)
```


## Filter low-intensity peaks

```{r filter-intensity}
xdata <- refineChromPeaks(xdata, 
                          param = FilterIntensityParam(
                            nValues = 5, threshold = int)
)
```


## Peak post-processing

```{r peak-postproc}
mnp <- MergeNeighboringPeaksParam(
  expandRt = 2, 
  expandMz = 0.001, 
  ppm = 10,
  minProp = 0.66)
register(SerialParam())
xdata <- refineChromPeaks(xdata, param = mnp)
```


# Aligment

```{r aligment, eval = TRUE}
# Define the hook peaks
pdp <- PeakDensityParam(sampleGroups = xdata$type,
                        minFraction = 0.75,
                        binSize = 0.02,
                        bw = 3)
xdata <- groupChromPeaks(xdata, param = pdp)
# Perform the aligment
pgp <- PeakGroupsParam(span = 0.3,
                       subset = which(xdata$type == "xQC"),
                       subsetAdjust = "average",
                       minFraction = 1)
xdata <- adjustRtime(xdata, param = pgp)
```


## Checking

The results from the alignment are shown below. 
To visualize the alignment results, the BPC for the whole data set is plotted.

```{r alignment-rtime-plot, fig.width = 12, fig.height = 10, eval = TRUE}
chr_raw <- chromatogram(xdata, aggregationFun = "max", 
                        adjustedRtime = FALSE)
chr_adj <- chromatogram(xdata, aggregationFun = "max")
par(mfrow = c(3, 1), mar = c(0, 4.3, 2, 0.1))
plot(chr_raw, col = paste0(col_type[chr_raw$type], 40),
     peakType = "none", main = "BPC, raw")
plot(chr_adj, col = paste0(col_type[chr_raw$type], 40),
     peakType = "none", main = "BPC, adjusted")
plotAdjustedRtime(xdata, col = paste0(col_type[chr_raw$type], 80))
```


# Correspondance

```{r correspondance}
pdp <- PeakDensityParam(sampleGroups = xdata$type,
                        minFraction = 0.66,
                        minSamples = 1,
                        binSize = 0.02,
                        bw = 1)
xdata <- groupChromPeaks(xdata, param = pdp)
```


# Peak filling

```{r peak-filling}
fcp <- ChromPeakAreaParam()
xdata <- fillChromPeaks(xdata, param = fcp)
```


# PCA

```{r pca, eval=TRUE}
data <- featureValues(xdata, method = "sum", value = "into")
set.seed(123)
data <- t(imputeRowMinRand(data, method = "from_to",
                           min_fraction = 1/100,
                           min_fraction_from = 1/1000
))
dt <- log10(data)
scaling.pareto <- BioMark::scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = gsub(".mzData", "", rownames(tmp)),
        color = xdata$type)
features <- data.frame(featureDefinitions(xdata))
tmp <- data.frame(pca$rotation)
rownames(tmp) <- paste(sprintf("%.4f",round(features$mzmed, 4)), 
                       sprintf("%.2f",round(features$rtmed/60, 2)), 
                       sep = "_")
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp))

dt <- data[xdata$type == "study",]
dt <- log10(dt)
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = gsub(".mzData", "", rownames(tmp)),
        color = as.numeric(substr(rownames(tmp), 2, 4)))
```

# Save data

```{r save}
save(xdata, file = paste0("data/RData/data_XCMS_", polarity, ".RData"))
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```